/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/[index]'
import { Route as RouteRouteImport } from './routes/[route]'
import { Route as LazyRouteImport } from './routes/[lazy]'
import { Route as BlogRouteImport } from './routes/blog[_]'
import { Route as LayoutRouteImport } from './routes/[_]layout'

const IndexRoute = IndexRouteImport.update({
  id: '/index',
  path: '/index',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteRoute = RouteRouteImport.update({
  id: '/route',
  path: '/route',
  getParentRoute: () => rootRouteImport,
} as any)
const LazyRoute = LazyRouteImport.update({
  id: '/lazy',
  path: '/lazy',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog_',
  path: '/blog_',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  path: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/_layout': typeof LayoutRoute
  '/blog_': typeof BlogRoute
  '/index': typeof IndexRoute
  '/lazy': typeof LazyRoute
  '/route': typeof RouteRoute
}
export interface FileRoutesByTo {
  '/_layout': typeof LayoutRoute
  '/blog_': typeof BlogRoute
  '/index': typeof IndexRoute
  '/lazy': typeof LazyRoute
  '/route': typeof RouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRoute
  '/blog_': typeof BlogRoute
  '/index': typeof IndexRoute
  '/lazy': typeof LazyRoute
  '/route': typeof RouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/_layout' | '/blog_' | '/index' | '/lazy' | '/route'
  fileRoutesByTo: FileRoutesByTo
  to: '/_layout' | '/blog_' | '/index' | '/lazy' | '/route'
  id: '__root__' | '/_layout' | '/blog_' | '/index' | '/lazy' | '/route'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRoute
  BlogRoute: typeof BlogRoute
  IndexRoute: typeof IndexRoute
  LazyRoute: typeof LazyRoute
  RouteRoute: typeof RouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/index': {
      id: '/index'
      path: '/index'
      fullPath: '/index'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route': {
      id: '/route'
      path: '/route'
      fullPath: '/route'
      preLoaderRoute: typeof RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lazy': {
      id: '/lazy'
      path: '/lazy'
      fullPath: '/lazy'
      preLoaderRoute: typeof LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_': {
      id: '/blog_'
      path: '/blog_'
      fullPath: '/blog_'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: '/_layout'
      fullPath: '/_layout'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRoute,
  BlogRoute: BlogRoute,
  IndexRoute: IndexRoute,
  LazyRoute: LazyRoute,
  RouteRoute: RouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
