/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'
import { default as ContactLazyRouteComponent } from './routes/contact.lazy.mdx'
import { default as AboutRouteComponent } from './routes/about.mdx'
import { default as PostsIndexRouteComponent } from './routes/posts/index.mdx'
import { default as BlogIndexRouteComponent } from './routes/blog.index.mdx'
import { default as PostsPostIdRouteComponent } from './routes/posts/$postId.mdx'
import { default as LayoutFaqRouteComponent } from './routes/_layout/faq.mdx'
import { default as marketingPricingRouteComponent } from './routes/(marketing)/pricing.mdx'

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as PostsRouteRouteImport } from './routes/posts/route'
import { Route as IndexRouteImport } from './routes/index'

const ContactLazyRouteImport = createFileRoute('/contact')()
const AboutRouteImport = createFileRoute('/about')()
const PostsIndexRouteImport = createFileRoute('/posts/')()
const BlogIndexRouteImport = createFileRoute('/blog/')()
const PostsPostIdRouteImport = createFileRoute('/posts/$postId')()
const LayoutFaqRouteImport = createFileRoute('/_layout/faq')()
const marketingPricingRouteImport = createFileRoute('/(marketing)/pricing')()

const ContactLazyRoute = ContactLazyRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
  .lazy(() => import('./routes/contact.lazy.mdx').then((d) => d.default))
  .update({ component: ContactLazyRouteComponent })
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).update({ component: AboutRouteComponent })
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRouteRoute = PostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRouteRoute,
} as any).update({ component: PostsIndexRouteComponent })
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any).update({ component: BlogIndexRouteComponent })
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRouteRoute,
} as any).update({ component: PostsPostIdRouteComponent })
const LayoutFaqRoute = LayoutFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => LayoutRoute,
} as any).update({ component: LayoutFaqRouteComponent })
const marketingPricingRoute = marketingPricingRouteImport
  .update({
    id: '/(marketing)/pricing',
    path: '/pricing',
    getParentRoute: () => rootRouteImport,
  } as any)
  .update({ component: marketingPricingRouteComponent })

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/posts': typeof PostsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/docs': typeof DocsRoute
  '/contact': typeof ContactLazyRoute
  '/pricing': typeof marketingPricingRoute
  '/faq': typeof LayoutFaqRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/blog': typeof BlogIndexRoute
  '/posts/': typeof PostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docs': typeof DocsRoute
  '/contact': typeof ContactLazyRoute
  '/pricing': typeof marketingPricingRoute
  '/faq': typeof LayoutFaqRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/blog': typeof BlogIndexRoute
  '/posts': typeof PostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/posts': typeof PostsRouteRouteWithChildren
  '/_layout': typeof LayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/docs': typeof DocsRoute
  '/contact': typeof ContactLazyRoute
  '/(marketing)/pricing': typeof marketingPricingRoute
  '/_layout/faq': typeof LayoutFaqRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/blog/': typeof BlogIndexRoute
  '/posts/': typeof PostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/posts'
    | '/about'
    | '/docs'
    | '/contact'
    | '/pricing'
    | '/faq'
    | '/posts/$postId'
    | '/blog'
    | '/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/docs'
    | '/contact'
    | '/pricing'
    | '/faq'
    | '/posts/$postId'
    | '/blog'
    | '/posts'
  id:
    | '__root__'
    | '/'
    | '/posts'
    | '/_layout'
    | '/about'
    | '/docs'
    | '/contact'
    | '/(marketing)/pricing'
    | '/_layout/faq'
    | '/posts/$postId'
    | '/blog/'
    | '/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostsRouteRoute: typeof PostsRouteRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
  AboutRoute: typeof AboutRoute
  DocsRoute: typeof DocsRoute
  ContactLazyRoute: typeof ContactLazyRoute
  marketingPricingRoute: typeof marketingPricingRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/_layout/faq': {
      id: '/_layout/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof LayoutFaqRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/(marketing)/pricing': {
      id: '/(marketing)/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof marketingPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PostsRouteRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

const PostsRouteRouteChildren: PostsRouteRouteChildren = {
  PostsPostIdRoute: PostsPostIdRoute,
  PostsIndexRoute: PostsIndexRoute,
}

const PostsRouteRouteWithChildren = PostsRouteRoute._addFileChildren(
  PostsRouteRouteChildren,
)

interface LayoutRouteChildren {
  LayoutFaqRoute: typeof LayoutFaqRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutFaqRoute: LayoutFaqRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostsRouteRoute: PostsRouteRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
  AboutRoute: AboutRoute,
  DocsRoute: DocsRoute,
  ContactLazyRoute: ContactLazyRoute,
  marketingPricingRoute: marketingPricingRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
