/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StreamRouteImport } from './routes/stream'
import { Route as DataOnlyRouteImport } from './routes/data-only'
import { Route as SsrRouteImport } from './routes/_ssr'
import { Route as IndexRouteImport } from './routes/index'

const StreamRoute = StreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const DataOnlyRoute = DataOnlyRouteImport.update({
  id: '/data-only',
  path: '/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const SsrRoute = SsrRouteImport.update({
  id: '/_ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data-only': typeof DataOnlyRoute
  '/stream': typeof StreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data-only': typeof DataOnlyRoute
  '/stream': typeof StreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_ssr': typeof SsrRoute
  '/data-only': typeof DataOnlyRoute
  '/stream': typeof StreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/data-only' | '/stream'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/data-only' | '/stream'
  id: '__root__' | '/' | '/_ssr' | '/data-only' | '/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SsrRoute: typeof SsrRoute
  DataOnlyRoute: typeof DataOnlyRoute
  StreamRoute: typeof StreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stream': {
      id: '/stream'
      path: '/stream'
      fullPath: '/stream'
      preLoaderRoute: typeof StreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-only': {
      id: '/data-only'
      path: '/data-only'
      fullPath: '/data-only'
      preLoaderRoute: typeof DataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_ssr': {
      id: '/_ssr'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SsrRoute: SsrRoute,
  DataOnlyRoute: DataOnlyRoute,
  StreamRoute: StreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
