packages:
  - 'packages/*'
  - 'examples/react/*'
  - 'examples/solid/*'
  - 'examples/react/router-monorepo-react-query/packages/*'
  - 'examples/react/router-monorepo-simple/packages/*'
  - 'examples/react/router-monorepo-simple-lazy/packages/*'
  - 'e2e/e2e-utils'
  - 'e2e/react-router/*'
  - 'e2e/solid-router/*'
  - 'e2e/react-start/*'

catalogs:
  # Can be referenced through "catalog:react"
  react:
    react: 19.0.0
    react-dom: 19.0.0

  # Can be referenced through "catalog:peer-react"
  peer-react:
    react: '>=18.0.0 || >=19.0.0'
    react-dom: '>=18.0.0 || >=19.0.0'
