cleanupUnusedCatalogs: true
linkWorkspacePackages: true
preferWorkspacePackages: true

packages:
  - 'packages/*'
  - 'examples/react/*'
  - 'examples/solid/*'
  - 'examples/vue/*'
  - 'examples/react/router-monorepo-react-query/packages/*'
  - 'examples/react/router-monorepo-simple/packages/*'
  - 'examples/react/router-monorepo-simple-lazy/packages/*'
  - 'e2e/e2e-utils'
  - 'e2e/react-router/*'
  - 'e2e/solid-router/*'
  - 'e2e/vue-router/*'
  - 'e2e/react-start/*'
  - 'e2e/solid-start/*'
  - 'e2e/vue-start/*'
