/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as testsWithSearchRouteImport } from './routes/(tests)/with-search'
import { Route as testsWithLoaderRouteImport } from './routes/(tests)/with-loader'
import { Route as testsNormalPageRouteImport } from './routes/(tests)/normal-page'
import { Route as testsNestedScrollSearchRouteImport } from './routes/(tests)/nested-scroll-search'
import { Route as testsNestedScrollCarryOverBRouteImport } from './routes/(tests)/nested-scroll-carry-over-b'
import { Route as testsNestedScrollCarryOverARouteImport } from './routes/(tests)/nested-scroll-carry-over-a'
import { Route as testsNestedScrollAwayRouteImport } from './routes/(tests)/nested-scroll-away'
import { Route as testsHashScrollReproRouteImport } from './routes/(tests)/hash-scroll-repro'
import { Route as testsHashScrollAboutRouteImport } from './routes/(tests)/hash-scroll-about'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const testsWithSearchRoute = testsWithSearchRouteImport.update({
  id: '/(tests)/with-search',
  path: '/with-search',
  getParentRoute: () => rootRouteImport,
} as any)
const testsWithLoaderRoute = testsWithLoaderRouteImport.update({
  id: '/(tests)/with-loader',
  path: '/with-loader',
  getParentRoute: () => rootRouteImport,
} as any)
const testsNormalPageRoute = testsNormalPageRouteImport.update({
  id: '/(tests)/normal-page',
  path: '/normal-page',
  getParentRoute: () => rootRouteImport,
} as any)
const testsNestedScrollSearchRoute = testsNestedScrollSearchRouteImport.update({
  id: '/(tests)/nested-scroll-search',
  path: '/nested-scroll-search',
  getParentRoute: () => rootRouteImport,
} as any)
const testsNestedScrollCarryOverBRoute =
  testsNestedScrollCarryOverBRouteImport.update({
    id: '/(tests)/nested-scroll-carry-over-b',
    path: '/nested-scroll-carry-over-b',
    getParentRoute: () => rootRouteImport,
  } as any)
const testsNestedScrollCarryOverARoute =
  testsNestedScrollCarryOverARouteImport.update({
    id: '/(tests)/nested-scroll-carry-over-a',
    path: '/nested-scroll-carry-over-a',
    getParentRoute: () => rootRouteImport,
  } as any)
const testsNestedScrollAwayRoute = testsNestedScrollAwayRouteImport.update({
  id: '/(tests)/nested-scroll-away',
  path: '/nested-scroll-away',
  getParentRoute: () => rootRouteImport,
} as any)
const testsHashScrollReproRoute = testsHashScrollReproRouteImport.update({
  id: '/(tests)/hash-scroll-repro',
  path: '/hash-scroll-repro',
  getParentRoute: () => rootRouteImport,
} as any)
const testsHashScrollAboutRoute = testsHashScrollAboutRouteImport.update({
  id: '/(tests)/hash-scroll-about',
  path: '/hash-scroll-about',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hash-scroll-about': typeof testsHashScrollAboutRoute
  '/hash-scroll-repro': typeof testsHashScrollReproRoute
  '/nested-scroll-away': typeof testsNestedScrollAwayRoute
  '/nested-scroll-carry-over-a': typeof testsNestedScrollCarryOverARoute
  '/nested-scroll-carry-over-b': typeof testsNestedScrollCarryOverBRoute
  '/nested-scroll-search': typeof testsNestedScrollSearchRoute
  '/normal-page': typeof testsNormalPageRoute
  '/with-loader': typeof testsWithLoaderRoute
  '/with-search': typeof testsWithSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hash-scroll-about': typeof testsHashScrollAboutRoute
  '/hash-scroll-repro': typeof testsHashScrollReproRoute
  '/nested-scroll-away': typeof testsNestedScrollAwayRoute
  '/nested-scroll-carry-over-a': typeof testsNestedScrollCarryOverARoute
  '/nested-scroll-carry-over-b': typeof testsNestedScrollCarryOverBRoute
  '/nested-scroll-search': typeof testsNestedScrollSearchRoute
  '/normal-page': typeof testsNormalPageRoute
  '/with-loader': typeof testsWithLoaderRoute
  '/with-search': typeof testsWithSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(tests)/hash-scroll-about': typeof testsHashScrollAboutRoute
  '/(tests)/hash-scroll-repro': typeof testsHashScrollReproRoute
  '/(tests)/nested-scroll-away': typeof testsNestedScrollAwayRoute
  '/(tests)/nested-scroll-carry-over-a': typeof testsNestedScrollCarryOverARoute
  '/(tests)/nested-scroll-carry-over-b': typeof testsNestedScrollCarryOverBRoute
  '/(tests)/nested-scroll-search': typeof testsNestedScrollSearchRoute
  '/(tests)/normal-page': typeof testsNormalPageRoute
  '/(tests)/with-loader': typeof testsWithLoaderRoute
  '/(tests)/with-search': typeof testsWithSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hash-scroll-about'
    | '/hash-scroll-repro'
    | '/nested-scroll-away'
    | '/nested-scroll-carry-over-a'
    | '/nested-scroll-carry-over-b'
    | '/nested-scroll-search'
    | '/normal-page'
    | '/with-loader'
    | '/with-search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hash-scroll-about'
    | '/hash-scroll-repro'
    | '/nested-scroll-away'
    | '/nested-scroll-carry-over-a'
    | '/nested-scroll-carry-over-b'
    | '/nested-scroll-search'
    | '/normal-page'
    | '/with-loader'
    | '/with-search'
  id:
    | '__root__'
    | '/'
    | '/(tests)/hash-scroll-about'
    | '/(tests)/hash-scroll-repro'
    | '/(tests)/nested-scroll-away'
    | '/(tests)/nested-scroll-carry-over-a'
    | '/(tests)/nested-scroll-carry-over-b'
    | '/(tests)/nested-scroll-search'
    | '/(tests)/normal-page'
    | '/(tests)/with-loader'
    | '/(tests)/with-search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  testsHashScrollAboutRoute: typeof testsHashScrollAboutRoute
  testsHashScrollReproRoute: typeof testsHashScrollReproRoute
  testsNestedScrollAwayRoute: typeof testsNestedScrollAwayRoute
  testsNestedScrollCarryOverARoute: typeof testsNestedScrollCarryOverARoute
  testsNestedScrollCarryOverBRoute: typeof testsNestedScrollCarryOverBRoute
  testsNestedScrollSearchRoute: typeof testsNestedScrollSearchRoute
  testsNormalPageRoute: typeof testsNormalPageRoute
  testsWithLoaderRoute: typeof testsWithLoaderRoute
  testsWithSearchRoute: typeof testsWithSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tests)/with-search': {
      id: '/(tests)/with-search'
      path: '/with-search'
      fullPath: '/with-search'
      preLoaderRoute: typeof testsWithSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tests)/with-loader': {
      id: '/(tests)/with-loader'
      path: '/with-loader'
      fullPath: '/with-loader'
      preLoaderRoute: typeof testsWithLoaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tests)/normal-page': {
      id: '/(tests)/normal-page'
      path: '/normal-page'
      fullPath: '/normal-page'
      preLoaderRoute: typeof testsNormalPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tests)/nested-scroll-search': {
      id: '/(tests)/nested-scroll-search'
      path: '/nested-scroll-search'
      fullPath: '/nested-scroll-search'
      preLoaderRoute: typeof testsNestedScrollSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tests)/nested-scroll-carry-over-b': {
      id: '/(tests)/nested-scroll-carry-over-b'
      path: '/nested-scroll-carry-over-b'
      fullPath: '/nested-scroll-carry-over-b'
      preLoaderRoute: typeof testsNestedScrollCarryOverBRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tests)/nested-scroll-carry-over-a': {
      id: '/(tests)/nested-scroll-carry-over-a'
      path: '/nested-scroll-carry-over-a'
      fullPath: '/nested-scroll-carry-over-a'
      preLoaderRoute: typeof testsNestedScrollCarryOverARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tests)/nested-scroll-away': {
      id: '/(tests)/nested-scroll-away'
      path: '/nested-scroll-away'
      fullPath: '/nested-scroll-away'
      preLoaderRoute: typeof testsNestedScrollAwayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tests)/hash-scroll-repro': {
      id: '/(tests)/hash-scroll-repro'
      path: '/hash-scroll-repro'
      fullPath: '/hash-scroll-repro'
      preLoaderRoute: typeof testsHashScrollReproRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tests)/hash-scroll-about': {
      id: '/(tests)/hash-scroll-about'
      path: '/hash-scroll-about'
      fullPath: '/hash-scroll-about'
      preLoaderRoute: typeof testsHashScrollAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  testsHashScrollAboutRoute: testsHashScrollAboutRoute,
  testsHashScrollReproRoute: testsHashScrollReproRoute,
  testsNestedScrollAwayRoute: testsNestedScrollAwayRoute,
  testsNestedScrollCarryOverARoute: testsNestedScrollCarryOverARoute,
  testsNestedScrollCarryOverBRoute: testsNestedScrollCarryOverBRoute,
  testsNestedScrollSearchRoute: testsNestedScrollSearchRoute,
  testsNormalPageRoute: testsNormalPageRoute,
  testsWithLoaderRoute: testsWithLoaderRoute,
  testsWithSearchRoute: testsWithSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
