/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as testTemplateLiteralRouteImport } from './routes/(test)/template-literal'
import { Route as testInitiallyLazyRouteImport } from './routes/(test)/initiallyLazy'
import { Route as testInitiallyEmptyRouteImport } from './routes/(test)/initiallyEmpty'
import { Route as testFooRouteImport } from './routes/(test)/foo'
import { Route as testDuplicateImportRouteImport } from './routes/(test)/duplicate-import'
import { Route as testDoubleQuotesRouteImport } from './routes/(test)/double-quotes'
import { Route as testFooBarRouteImport } from './routes/(test)/foo.bar'

const testBarLazyRouteImport = createFileRoute('/(test)/bar')()

const testBarLazyRoute = testBarLazyRouteImport
  .update({
    id: '/(test)/bar',
    path: '/bar',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(test)/bar.lazy').then((d) => d.Route))
const testTemplateLiteralRoute = testTemplateLiteralRouteImport.update({
  id: '/(test)/template-literal',
  path: '/template-literal',
  getParentRoute: () => rootRouteImport,
} as any)
const testInitiallyLazyRoute = testInitiallyLazyRouteImport.update({
  id: '/(test)/initiallyLazy',
  path: '/initiallyLazy',
  getParentRoute: () => rootRouteImport,
} as any)
const testInitiallyEmptyRoute = testInitiallyEmptyRouteImport
  .update({
    id: '/(test)/initiallyEmpty',
    path: '/initiallyEmpty',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(test)/initiallyEmpty.lazy').then((d) => d.Route),
  )
const testFooRoute = testFooRouteImport.update({
  id: '/(test)/foo',
  path: '/foo',
  getParentRoute: () => rootRouteImport,
} as any)
const testDuplicateImportRoute = testDuplicateImportRouteImport.update({
  id: '/(test)/duplicate-import',
  path: '/duplicate-import',
  getParentRoute: () => rootRouteImport,
} as any)
const testDoubleQuotesRoute = testDoubleQuotesRouteImport.update({
  id: '/(test)/double-quotes',
  path: '/double-quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const testFooBarRoute = testFooBarRouteImport.update({
  id: '/bar',
  path: '/bar',
  getParentRoute: () => testFooRoute,
} as any)

export interface FileRoutesByFullPath {
  '/double-quotes': typeof testDoubleQuotesRoute
  '/duplicate-import': typeof testDuplicateImportRoute
  '/foo': typeof testFooRouteWithChildren
  '/initiallyEmpty': typeof testInitiallyEmptyRoute
  '/initiallyLazy': typeof testInitiallyLazyRoute
  '/template-literal': typeof testTemplateLiteralRoute
  '/bar': typeof testBarLazyRoute
  '/foo/bar': typeof testFooBarRoute
}
export interface FileRoutesByTo {
  '/double-quotes': typeof testDoubleQuotesRoute
  '/duplicate-import': typeof testDuplicateImportRoute
  '/foo': typeof testFooRouteWithChildren
  '/initiallyEmpty': typeof testInitiallyEmptyRoute
  '/initiallyLazy': typeof testInitiallyLazyRoute
  '/template-literal': typeof testTemplateLiteralRoute
  '/bar': typeof testBarLazyRoute
  '/foo/bar': typeof testFooBarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(test)/double-quotes': typeof testDoubleQuotesRoute
  '/(test)/duplicate-import': typeof testDuplicateImportRoute
  '/(test)/foo': typeof testFooRouteWithChildren
  '/(test)/initiallyEmpty': typeof testInitiallyEmptyRoute
  '/(test)/initiallyLazy': typeof testInitiallyLazyRoute
  '/(test)/template-literal': typeof testTemplateLiteralRoute
  '/(test)/bar': typeof testBarLazyRoute
  '/(test)/foo/bar': typeof testFooBarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/double-quotes'
    | '/duplicate-import'
    | '/foo'
    | '/initiallyEmpty'
    | '/initiallyLazy'
    | '/template-literal'
    | '/bar'
    | '/foo/bar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/double-quotes'
    | '/duplicate-import'
    | '/foo'
    | '/initiallyEmpty'
    | '/initiallyLazy'
    | '/template-literal'
    | '/bar'
    | '/foo/bar'
  id:
    | '__root__'
    | '/(test)/double-quotes'
    | '/(test)/duplicate-import'
    | '/(test)/foo'
    | '/(test)/initiallyEmpty'
    | '/(test)/initiallyLazy'
    | '/(test)/template-literal'
    | '/(test)/bar'
    | '/(test)/foo/bar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  testDoubleQuotesRoute: typeof testDoubleQuotesRoute
  testDuplicateImportRoute: typeof testDuplicateImportRoute
  testFooRoute: typeof testFooRouteWithChildren
  testInitiallyEmptyRoute: typeof testInitiallyEmptyRoute
  testInitiallyLazyRoute: typeof testInitiallyLazyRoute
  testTemplateLiteralRoute: typeof testTemplateLiteralRoute
  testBarLazyRoute: typeof testBarLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(test)/bar': {
      id: '/(test)/bar'
      path: '/bar'
      fullPath: '/bar'
      preLoaderRoute: typeof testBarLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(test)/template-literal': {
      id: '/(test)/template-literal'
      path: '/template-literal'
      fullPath: '/template-literal'
      preLoaderRoute: typeof testTemplateLiteralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(test)/initiallyLazy': {
      id: '/(test)/initiallyLazy'
      path: '/initiallyLazy'
      fullPath: '/initiallyLazy'
      preLoaderRoute: typeof testInitiallyLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(test)/initiallyEmpty': {
      id: '/(test)/initiallyEmpty'
      path: '/initiallyEmpty'
      fullPath: '/initiallyEmpty'
      preLoaderRoute: typeof testInitiallyEmptyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(test)/foo': {
      id: '/(test)/foo'
      path: '/foo'
      fullPath: '/foo'
      preLoaderRoute: typeof testFooRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(test)/duplicate-import': {
      id: '/(test)/duplicate-import'
      path: '/duplicate-import'
      fullPath: '/duplicate-import'
      preLoaderRoute: typeof testDuplicateImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(test)/double-quotes': {
      id: '/(test)/double-quotes'
      path: '/double-quotes'
      fullPath: '/double-quotes'
      preLoaderRoute: typeof testDoubleQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(test)/foo/bar': {
      id: '/(test)/foo/bar'
      path: '/bar'
      fullPath: '/foo/bar'
      preLoaderRoute: typeof testFooBarRouteImport
      parentRoute: typeof testFooRoute
    }
  }
}

interface testFooRouteChildren {
  testFooBarRoute: typeof testFooBarRoute
}

const testFooRouteChildren: testFooRouteChildren = {
  testFooBarRoute: testFooBarRoute,
}

const testFooRouteWithChildren =
  testFooRoute._addFileChildren(testFooRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  testDoubleQuotesRoute: testDoubleQuotesRoute,
  testDuplicateImportRoute: testDuplicateImportRoute,
  testFooRoute: testFooRouteWithChildren,
  testInitiallyEmptyRoute: testInitiallyEmptyRoute,
  testInitiallyLazyRoute: testInitiallyLazyRoute,
  testTemplateLiteralRoute: testTemplateLiteralRoute,
  testBarLazyRoute: testBarLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
