import { describe, expect, it } from 'vitest'
import { createLRUCache } from '../src/lru-cache'

describe('LRU Cache', () => {
  it('evicts oldest set', () => {
    const cache = createLRUCache<string, number>(3)
    cache.set('a', 1)
    cache.set('b', 2)
    cache.set('c', 3)
    cache.set('d', 4) // 'a' should be evicted
    expect(cache.get('a')).toBeUndefined()
    expect(cache.get('b')).toBe(2)
  })
  it('evicts oldest used', () => {
    const cache = createLRUCache<string, number>(3)
    cache.set('a', 1)
    cache.set('b', 2)
    cache.set('c', 3)
    cache.get('a') // 'a' is now the most recently used
    cache.set('d', 4) // 'b' should be evicted
    expect(cache.get('b')).toBeUndefined()
    expect(cache.get('a')).toBe(1)
  })
  it('does not change order on a missing get', () => {
    const cache = createLRUCache<string, number>(2)
    cache.set('a', 1)
    cache.set('b', 2)
    expect(cache.get('x')).toBeUndefined()
    cache.set('c', 3)
    expect(cache.get('a')).toBeUndefined()
    expect(cache.get('b')).toBe(2)
  })
  it('moves updated entries to most recently used before capacity is reached', () => {
    const cache = createLRUCache<string, number>(3)
    cache.set('a', 1)
    cache.set('b', 2)
    cache.set('a', 3)
    cache.set('c', 4)
    cache.set('d', 5)
    expect(cache.get('b')).toBeUndefined()
    expect(cache.get('a')).toBe(3)
  })
  it('updates existing entries without evicting when full', () => {
    const cache = createLRUCache<string, number>(3)
    cache.set('a', 1)
    cache.set('b', 2)
    cache.set('c', 3)
    cache.set('b', 4)
    expect(cache.get('a')).toBe(1)
    expect(cache.get('b')).toBe(4)
  })
  it('moves updated oldest entries to most recently used when full', () => {
    const cache = createLRUCache<string, number>(3)
    cache.set('a', 1)
    cache.set('b', 2)
    cache.set('c', 3)
    cache.set('a', 4)
    cache.set('d', 5)
    expect(cache.get('b')).toBeUndefined()
    expect(cache.get('a')).toBe(4)
  })
  it('keeps updated newest entries most recently used when full', () => {
    const cache = createLRUCache<string, number>(3)
    cache.set('a', 1)
    cache.set('b', 2)
    cache.set('c', 3)
    cache.set('c', 4)
    cache.set('d', 5)
    expect(cache.get('a')).toBeUndefined()
    expect(cache.get('c')).toBe(4)
  })
  it('handles repeated updates without duplicating entries', () => {
    const cache = createLRUCache<string, number>(3)
    cache.set('a', 1)
    cache.set('b', 2)
    cache.set('c', 3)
    cache.set('a', 4)
    cache.set('a', 5)
    cache.set('b', 6)
    cache.set('d', 7)
    expect(cache.get('c')).toBeUndefined()
    expect(cache.get('a')).toBe(5)
    expect(cache.get('b')).toBe(6)
  })
  it('moves middle entries to most recently used on get', () => {
    const cache = createLRUCache<string, number>(3)
    cache.set('a', 1)
    cache.set('b', 2)
    cache.set('c', 3)
    expect(cache.get('b')).toBe(2)
    cache.set('d', 4)
    expect(cache.get('a')).toBeUndefined()
    expect(cache.get('c')).toBe(3)
    expect(cache.get('b')).toBe(2)
  })
  it('clears entries and reuses the cache', () => {
    const cache = createLRUCache<string, number>(2)
    cache.clear()
    cache.set('a', 1)
    cache.set('b', 2)
    cache.get('a')
    cache.clear()
    cache.clear()
    expect(cache.get('a')).toBeUndefined()
    cache.set('c', 3)
    cache.set('d', 4)
    cache.set('e', 5)
    expect(cache.get('c')).toBeUndefined()
    expect(cache.get('d')).toBe(4)
  })
  it('handles a max size of one', () => {
    const cache = createLRUCache<string, number | undefined>(1)
    cache.set('a', undefined)
    expect(cache.get('a')).toBeUndefined()
    cache.set('a', 2)
    expect(cache.get('a')).toBe(2)
    cache.set('b', 3)
    expect(cache.get('a')).toBeUndefined()
    expect(cache.get('b')).toBe(3)
  })
  it('caches undefined values', () => {
    const cache = createLRUCache<string, number | undefined>(2)
    cache.set('a', undefined)
    cache.set('b', 2)
    expect(cache.get('a')).toBeUndefined()
    cache.set('c', 3)
    expect(cache.get('b')).toBeUndefined()
  })
  it('uses non-string keys by identity', () => {
    const cache = createLRUCache<object, number>(2)
    const a = { id: 'a' }
    const b = { id: 'b' }
    const aLike = { id: 'a' }
    cache.set(a, 1)
    cache.set(b, 2)
    expect(cache.get(aLike)).toBeUndefined()
    expect(cache.get(a)).toBe(1)
    cache.set({ id: 'c' }, 3)
    expect(cache.get(b)).toBeUndefined()
  })
})
