/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlphaRouteImport } from './routes/alpha'
import { Route as BetaRouteImport } from './routes/beta'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as SassMixinRouteImport } from './routes/sass-mixin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlphaRoute = AlphaRouteImport.update({
  id: '/alpha',
  path: '/alpha',
  getParentRoute: () => rootRouteImport,
} as any)
const BetaRoute = BetaRouteImport.update({
  id: '/beta',
  path: '/beta',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const SassMixinRoute = SassMixinRouteImport.update({
  id: '/sass-mixin',
  path: '/sass-mixin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alpha': typeof AlphaRoute
  '/beta': typeof BetaRoute
  '/modules': typeof ModulesRoute
  '/quotes': typeof QuotesRoute
  '/sass-mixin': typeof SassMixinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alpha': typeof AlphaRoute
  '/beta': typeof BetaRoute
  '/modules': typeof ModulesRoute
  '/quotes': typeof QuotesRoute
  '/sass-mixin': typeof SassMixinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alpha': typeof AlphaRoute
  '/beta': typeof BetaRoute
  '/modules': typeof ModulesRoute
  '/quotes': typeof QuotesRoute
  '/sass-mixin': typeof SassMixinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/alpha' | '/beta' | '/modules' | '/quotes' | '/sass-mixin'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alpha' | '/beta' | '/modules' | '/quotes' | '/sass-mixin'
  id:
    | '__root__'
    | '/'
    | '/alpha'
    | '/beta'
    | '/modules'
    | '/quotes'
    | '/sass-mixin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlphaRoute: typeof AlphaRoute
  BetaRoute: typeof BetaRoute
  ModulesRoute: typeof ModulesRoute
  QuotesRoute: typeof QuotesRoute
  SassMixinRoute: typeof SassMixinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alpha': {
      id: '/alpha'
      path: '/alpha'
      fullPath: '/alpha'
      preLoaderRoute: typeof AlphaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beta': {
      id: '/beta'
      path: '/beta'
      fullPath: '/beta'
      preLoaderRoute: typeof BetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sass-mixin': {
      id: '/sass-mixin'
      path: '/sass-mixin'
      fullPath: '/sass-mixin'
      preLoaderRoute: typeof SassMixinRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlphaRoute: AlphaRoute,
  BetaRoute: BetaRoute,
  ModulesRoute: ModulesRoute,
  QuotesRoute: QuotesRoute,
  SassMixinRoute: SassMixinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
