import { writeFileSync } from 'node:fs'
import path from 'pathe'
import type { GeneratorPlugin } from '@tanstack/router-generator'
import type { TanStackStartVitePluginCoreOptions } from '../../types'

export interface ModuleDeclarationPluginOptions {
  generatedRouteTreePath: string
  routerFilePath: string
  startFilePath: string | undefined
  corePluginOpts: TanStackStartVitePluginCoreOptions
}

/**
 * This plugin generates a separate .d.ts file for the module augmentation
 * that registers the router type with TanStack Start.
 *
 * By generating this in a separate .d.ts file instead of in the main
 * routeTree.gen.ts file, we avoid creating a circular dependency that
 * causes TDZ (Temporal Dead Zone) errors in Vite SSR.
 *
 * The circular dependency was:
 * - router.tsx imports routeTree from routeTree.gen.ts
 * - routeTree.gen.ts had `import type { getRouter } from './router.tsx'`
 *
 * Now the type import only exists in the .d.ts file, which TypeScript
 * uses for type checking but Vite doesn't process at runtime.
 */
export function moduleDeclarationPlugin(
  getOptions: () => ModuleDeclarationPluginOptions,
): GeneratorPlugin {
  return {
    name: 'module-declaration-plugin',
    onRouteTreeChanged: () => {
      const options = getOptions()
      const dtsContent = generateModuleDeclaration(options)
      const dtsPath = getDtsPath(options.generatedRouteTreePath)

      writeFileSync(dtsPath, dtsContent, 'utf-8')
    },
  }
}

function getDtsPath(generatedRouteTreePath: string): string {
  // Replace .ts or .tsx extension with .d.ts
  // e.g., routeTree.gen.ts -> routeTree.gen.d.ts
  return generatedRouteTreePath.replace(/\.tsx?$/, '.d.ts')
}

function generateModuleDeclaration(
  options: ModuleDeclarationPluginOptions,
): string {
  const { generatedRouteTreePath, routerFilePath, startFilePath, corePluginOpts } =
    options

  function getImportPath(absolutePath: string) {
    let relativePath = path.relative(
      path.dirname(generatedRouteTreePath),
      absolutePath,
    )

    if (!relativePath.startsWith('.')) {
      relativePath = './' + relativePath
    }

    // convert to POSIX-style for ESM imports (important on Windows)
    relativePath = relativePath.split(path.sep).join('/')
    return relativePath
  }

  const lines: Array<string> = [
    '// This file was automatically generated by TanStack Start.',
    '// It provides type declarations for the router registration.',
    '// This file is separate from routeTree.gen.ts to avoid circular dependencies',
    '// that can cause TDZ errors in Vite SSR.',
    '',
    `import type { getRouter } from '${getImportPath(routerFilePath)}'`,
  ]

  if (startFilePath) {
    lines.push(
      `import type { startInstance } from '${getImportPath(startFilePath)}'`,
    )
  } else {
    // make sure we import something from start to get the server route declaration merge
    lines.push(
      `import type { createStart } from '@tanstack/${corePluginOpts.framework}-start'`,
    )
  }

  lines.push('')
  lines.push(`declare module '@tanstack/${corePluginOpts.framework}-start' {`)
  lines.push(`  interface Register {`)
  lines.push(`    ssr: true`)
  lines.push(`    router: Awaited<ReturnType<typeof getRouter>>`)

  if (startFilePath) {
    lines.push(
      `    config: Awaited<ReturnType<typeof startInstance.getOptions>>`,
    )
  }

  lines.push(`  }`)
  lines.push(`}`)
  lines.push('')

  return lines.join('\n')
}
