/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char91_1nd3xChar93RouteImport } from './routes/[_1nd3x]'
import { Route as BlogR0ut3RouteImport } from './routes/blog._r0ut3_'
import { Route as R1nd3xRouteImport } from './routes/_1nd3x'
import { Route as NestedChar91_1nd3xChar93RouteImport } from './routes/nested.[_1nd3x]'
import { Route as PostsChar91_r0ut3_Char93RouteImport } from './routes/posts.[_r0ut3_]'

const Char91_1nd3xChar93Route = Char91_1nd3xChar93RouteImport.update({
  id: '/_1nd3x',
  path: '/_1nd3x',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogR0ut3Route = BlogR0ut3RouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const R1nd3xRoute = R1nd3xRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NestedChar91_1nd3xChar93Route =
  NestedChar91_1nd3xChar93RouteImport.update({
    id: '/nested/_1nd3x',
    path: '/nested/_1nd3x',
    getParentRoute: () => rootRouteImport,
  } as any)
const PostsChar91_r0ut3_Char93Route =
  PostsChar91_r0ut3_Char93RouteImport.update({
    id: '/posts/_r0ut3_',
    path: '/posts/_r0ut3_',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof R1nd3xRoute
  '/blog': typeof BlogR0ut3Route
  '/_1nd3x': typeof Char91_1nd3xChar93Route
  '/nested/_1nd3x': typeof NestedChar91_1nd3xChar93Route
  '/posts/_r0ut3_': typeof PostsChar91_r0ut3_Char93Route
}
export interface FileRoutesByTo {
  '/': typeof R1nd3xRoute
  '/blog': typeof BlogR0ut3Route
  '/_1nd3x': typeof Char91_1nd3xChar93Route
  '/nested/_1nd3x': typeof NestedChar91_1nd3xChar93Route
  '/posts/_r0ut3_': typeof PostsChar91_r0ut3_Char93Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof R1nd3xRoute
  '/blog': typeof BlogR0ut3Route
  '/_1nd3x': typeof Char91_1nd3xChar93Route
  '/nested/_1nd3x': typeof NestedChar91_1nd3xChar93Route
  '/posts/_r0ut3_': typeof PostsChar91_r0ut3_Char93Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/blog' | '/_1nd3x' | '/nested/_1nd3x' | '/posts/_r0ut3_'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blog' | '/_1nd3x' | '/nested/_1nd3x' | '/posts/_r0ut3_'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/_1nd3x'
    | '/nested/_1nd3x'
    | '/posts/_r0ut3_'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  R1nd3xRoute: typeof R1nd3xRoute
  BlogR0ut3Route: typeof BlogR0ut3Route
  Char91_1nd3xChar93Route: typeof Char91_1nd3xChar93Route
  NestedChar91_1nd3xChar93Route: typeof NestedChar91_1nd3xChar93Route
  PostsChar91_r0ut3_Char93Route: typeof PostsChar91_r0ut3_Char93Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_1nd3x': {
      id: '/_1nd3x'
      path: '/_1nd3x'
      fullPath: '/_1nd3x'
      preLoaderRoute: typeof Char91_1nd3xChar93RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogR0ut3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof R1nd3xRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nested/_1nd3x': {
      id: '/nested/_1nd3x'
      path: '/nested/_1nd3x'
      fullPath: '/nested/_1nd3x'
      preLoaderRoute: typeof NestedChar91_1nd3xChar93RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/_r0ut3_': {
      id: '/posts/_r0ut3_'
      path: '/posts/_r0ut3_'
      fullPath: '/posts/_r0ut3_'
      preLoaderRoute: typeof PostsChar91_r0ut3_Char93RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  R1nd3xRoute: R1nd3xRoute,
  BlogR0ut3Route: BlogR0ut3Route,
  Char91_1nd3xChar93Route: Char91_1nd3xChar93Route,
  NestedChar91_1nd3xChar93Route: NestedChar91_1nd3xChar93Route,
  PostsChar91_r0ut3_Char93Route: PostsChar91_r0ut3_Char93Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
