/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteRouteImport } from './routes/_layout/route'

const LayoutPathLazyRouteImport = createFileRoute('/_layout/path')()
const LayoutPathIndexLazyRouteImport = createFileRoute('/_layout/path/')()

const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutPathLazyRoute = LayoutPathLazyRouteImport.update({
  id: '/path',
  path: '/path',
  getParentRoute: () => LayoutRouteRoute,
} as any).lazy(() => import('./routes/_layout/path.lazy').then((d) => d.Route))
const LayoutPathIndexLazyRoute = LayoutPathIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutPathLazyRoute,
} as any).lazy(() =>
  import('./routes/_layout/path.index.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof LayoutRouteRouteWithChildren
  '/path': typeof LayoutPathLazyRouteWithChildren
  '/path/': typeof LayoutPathIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutRouteRouteWithChildren
  '/path': typeof LayoutPathIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/_layout/path': typeof LayoutPathLazyRouteWithChildren
  '/_layout/path/': typeof LayoutPathIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/path' | '/path/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/path'
  id: '__root__' | '/_layout' | '/_layout/path' | '/_layout/path/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/path': {
      id: '/_layout/path'
      path: '/path'
      fullPath: '/path'
      preLoaderRoute: typeof LayoutPathLazyRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/path/': {
      id: '/_layout/path/'
      path: '/'
      fullPath: '/path/'
      preLoaderRoute: typeof LayoutPathIndexLazyRouteImport
      parentRoute: typeof LayoutPathLazyRoute
    }
  }
}

interface LayoutPathLazyRouteChildren {
  LayoutPathIndexLazyRoute: typeof LayoutPathIndexLazyRoute
}

const LayoutPathLazyRouteChildren: LayoutPathLazyRouteChildren = {
  LayoutPathIndexLazyRoute: LayoutPathIndexLazyRoute,
}

const LayoutPathLazyRouteWithChildren = LayoutPathLazyRoute._addFileChildren(
  LayoutPathLazyRouteChildren,
)

interface LayoutRouteRouteChildren {
  LayoutPathLazyRoute: typeof LayoutPathLazyRouteWithChildren
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutPathLazyRoute: LayoutPathLazyRouteWithChildren,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
