/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as nestedCallbackRouteImport } from './routes/nested/callback'
import { Route as nestedAuthRouteImport } from './routes/nested/auth'
import { Route as nestedHomeRouteImport } from './routes/nested/home'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const nestedCallbackRoute = nestedCallbackRouteImport.update({
  id: '/nested/_callback',
  path: '/nested/_callback',
  getParentRoute: () => rootRouteImport,
} as any)
const nestedAuthRoute = nestedAuthRouteImport.update({
  id: '/nested/_auth',
  path: '/nested/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const nestedHomeRoute = nestedHomeRouteImport.update({
  id: '/nested/',
  path: '/nested/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nested/': typeof nestedHomeRoute
  '/nested/_auth': typeof nestedAuthRoute
  '/nested/_callback': typeof nestedCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nested': typeof nestedHomeRoute
  '/nested/_auth': typeof nestedAuthRoute
  '/nested/_callback': typeof nestedCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/nested/': typeof nestedHomeRoute
  '/nested/_auth': typeof nestedAuthRoute
  '/nested/_callback': typeof nestedCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/nested/' | '/nested/_auth' | '/nested/_callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/nested' | '/nested/_auth' | '/nested/_callback'
  id: '__root__' | '/' | '/nested/' | '/nested/_auth' | '/nested/_callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  nestedHomeRoute: typeof nestedHomeRoute
  nestedAuthRoute: typeof nestedAuthRoute
  nestedCallbackRoute: typeof nestedCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nested/_callback': {
      id: '/nested/_callback'
      path: '/nested/_callback'
      fullPath: '/nested/_callback'
      preLoaderRoute: typeof nestedCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nested/_auth': {
      id: '/nested/_auth'
      path: '/nested/_auth'
      fullPath: '/nested/_auth'
      preLoaderRoute: typeof nestedAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nested/': {
      id: '/nested/'
      path: '/nested'
      fullPath: '/nested/'
      preLoaderRoute: typeof nestedHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  nestedHomeRoute: nestedHomeRoute,
  nestedAuthRoute: nestedAuthRoute,
  nestedCallbackRoute: nestedCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
