/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MergeMiddlewareContextRouteImport } from './routes/merge-middleware-context'
import { Route as MethodsRouteRouteImport } from './routes/methods/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MethodsIndexRouteImport } from './routes/methods/index'
import { Route as MethodsOnlyAnyRouteImport } from './routes/methods/only-any'
import { Route as ApiOnlyAnyRouteImport } from './routes/api/only-any'
import { Route as ApiMiddlewareContextRouteImport } from './routes/api/middleware-context'
import { Route as ApiHeadFallbackRouteImport } from './routes/api/head-fallback'
import { Route as ApiGetAndAnyRouteImport } from './routes/api/get-and-any'
import { Route as ApiHeadRedirectFallbackRouteImport } from './routes/api/head-redirect-fallback'
import { Route as ApiParamsFooRouteRouteImport } from './routes/api/params/$foo/route'
import { Route as ApiParamsFooBarRouteImport } from './routes/api/params/$foo/$bar'

const MergeMiddlewareContextRoute = MergeMiddlewareContextRouteImport.update({
  id: '/merge-middleware-context',
  path: '/merge-middleware-context',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodsRouteRoute = MethodsRouteRouteImport.update({
  id: '/methods',
  path: '/methods',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodsIndexRoute = MethodsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MethodsRouteRoute,
} as any)
const MethodsOnlyAnyRoute = MethodsOnlyAnyRouteImport.update({
  id: '/only-any',
  path: '/only-any',
  getParentRoute: () => MethodsRouteRoute,
} as any)
const ApiOnlyAnyRoute = ApiOnlyAnyRouteImport.update({
  id: '/api/only-any',
  path: '/api/only-any',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHeadFallbackRoute = ApiHeadFallbackRouteImport.update({
  id: '/api/head-fallback',
  path: '/api/head-fallback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGetAndAnyRoute = ApiGetAndAnyRouteImport.update({
  id: '/api/get-and-any',
  path: '/api/get-and-any',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHeadRedirectFallbackRoute = ApiHeadRedirectFallbackRouteImport.update({
  id: '/api/head-redirect-fallback',
  path: '/api/head-redirect-fallback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMiddlewareContextRoute = ApiMiddlewareContextRouteImport.update({
  id: '/api/middleware-context',
  path: '/api/middleware-context',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParamsFooRouteRoute = ApiParamsFooRouteRouteImport.update({
  id: '/api/params/$foo',
  path: '/api/params/$foo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParamsFooBarRoute = ApiParamsFooBarRouteImport.update({
  id: '/$bar',
  path: '/$bar',
  getParentRoute: () => ApiParamsFooRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/methods': typeof MethodsRouteRouteWithChildren
  '/merge-middleware-context': typeof MergeMiddlewareContextRoute
  '/api/middleware-context': typeof ApiMiddlewareContextRoute
  '/api/only-any': typeof ApiOnlyAnyRoute
  '/api/head-fallback': typeof ApiHeadFallbackRoute
  '/api/get-and-any': typeof ApiGetAndAnyRoute
  '/api/head-redirect-fallback': typeof ApiHeadRedirectFallbackRoute
  '/methods/only-any': typeof MethodsOnlyAnyRoute
  '/methods/': typeof MethodsIndexRoute
  '/api/params/$foo': typeof ApiParamsFooRouteRouteWithChildren
  '/api/params/$foo/$bar': typeof ApiParamsFooBarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/merge-middleware-context': typeof MergeMiddlewareContextRoute
  '/api/middleware-context': typeof ApiMiddlewareContextRoute
  '/api/only-any': typeof ApiOnlyAnyRoute
  '/api/head-fallback': typeof ApiHeadFallbackRoute
  '/api/get-and-any': typeof ApiGetAndAnyRoute
  '/api/head-redirect-fallback': typeof ApiHeadRedirectFallbackRoute
  '/methods/only-any': typeof MethodsOnlyAnyRoute
  '/methods': typeof MethodsIndexRoute
  '/api/params/$foo': typeof ApiParamsFooRouteRouteWithChildren
  '/api/params/$foo/$bar': typeof ApiParamsFooBarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/methods': typeof MethodsRouteRouteWithChildren
  '/merge-middleware-context': typeof MergeMiddlewareContextRoute
  '/api/middleware-context': typeof ApiMiddlewareContextRoute
  '/api/only-any': typeof ApiOnlyAnyRoute
  '/api/head-fallback': typeof ApiHeadFallbackRoute
  '/api/get-and-any': typeof ApiGetAndAnyRoute
  '/api/head-redirect-fallback': typeof ApiHeadRedirectFallbackRoute
  '/methods/only-any': typeof MethodsOnlyAnyRoute
  '/methods/': typeof MethodsIndexRoute
  '/api/params/$foo': typeof ApiParamsFooRouteRouteWithChildren
  '/api/params/$foo/$bar': typeof ApiParamsFooBarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/methods'
    | '/merge-middleware-context'
    | '/api/middleware-context'
    | '/api/only-any'
    | '/api/head-fallback'
    | '/api/get-and-any'
    | '/api/head-redirect-fallback'
    | '/methods/only-any'
    | '/methods/'
    | '/api/params/$foo'
    | '/api/params/$foo/$bar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/merge-middleware-context'
    | '/api/middleware-context'
    | '/api/only-any'
    | '/api/head-fallback'
    | '/api/get-and-any'
    | '/api/head-redirect-fallback'
    | '/methods/only-any'
    | '/methods'
    | '/api/params/$foo'
    | '/api/params/$foo/$bar'
  id:
    | '__root__'
    | '/'
    | '/methods'
    | '/merge-middleware-context'
    | '/api/middleware-context'
    | '/api/only-any'
    | '/api/head-fallback'
    | '/api/get-and-any'
    | '/api/head-redirect-fallback'
    | '/methods/only-any'
    | '/methods/'
    | '/api/params/$foo'
    | '/api/params/$foo/$bar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MethodsRouteRoute: typeof MethodsRouteRouteWithChildren
  MergeMiddlewareContextRoute: typeof MergeMiddlewareContextRoute
  ApiMiddlewareContextRoute: typeof ApiMiddlewareContextRoute
  ApiOnlyAnyRoute: typeof ApiOnlyAnyRoute
  ApiHeadFallbackRoute: typeof ApiHeadFallbackRoute
  ApiGetAndAnyRoute: typeof ApiGetAndAnyRoute
  ApiHeadRedirectFallbackRoute: typeof ApiHeadRedirectFallbackRoute
  ApiParamsFooRouteRoute: typeof ApiParamsFooRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/merge-middleware-context': {
      id: '/merge-middleware-context'
      path: '/merge-middleware-context'
      fullPath: '/merge-middleware-context'
      preLoaderRoute: typeof MergeMiddlewareContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methods': {
      id: '/methods'
      path: '/methods'
      fullPath: '/methods'
      preLoaderRoute: typeof MethodsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methods/': {
      id: '/methods/'
      path: '/'
      fullPath: '/methods/'
      preLoaderRoute: typeof MethodsIndexRouteImport
      parentRoute: typeof MethodsRouteRoute
    }
    '/methods/only-any': {
      id: '/methods/only-any'
      path: '/only-any'
      fullPath: '/methods/only-any'
      preLoaderRoute: typeof MethodsOnlyAnyRouteImport
      parentRoute: typeof MethodsRouteRoute
    }
    '/api/only-any': {
      id: '/api/only-any'
      path: '/api/only-any'
      fullPath: '/api/only-any'
      preLoaderRoute: typeof ApiOnlyAnyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/head-fallback': {
      id: '/api/head-fallback'
      path: '/api/head-fallback'
      fullPath: '/api/head-fallback'
      preLoaderRoute: typeof ApiHeadFallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/get-and-any': {
      id: '/api/get-and-any'
      path: '/api/get-and-any'
      fullPath: '/api/get-and-any'
      preLoaderRoute: typeof ApiGetAndAnyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/head-redirect-fallback': {
      id: '/api/head-redirect-fallback'
      path: '/api/head-redirect-fallback'
      fullPath: '/api/head-redirect-fallback'
      preLoaderRoute: typeof ApiHeadRedirectFallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/middleware-context': {
      id: '/api/middleware-context'
      path: '/api/middleware-context'
      fullPath: '/api/middleware-context'
      preLoaderRoute: typeof ApiMiddlewareContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/params/$foo': {
      id: '/api/params/$foo'
      path: '/api/params/$foo'
      fullPath: '/api/params/$foo'
      preLoaderRoute: typeof ApiParamsFooRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/params/$foo/$bar': {
      id: '/api/params/$foo/$bar'
      path: '/$bar'
      fullPath: '/api/params/$foo/$bar'
      preLoaderRoute: typeof ApiParamsFooBarRouteImport
      parentRoute: typeof ApiParamsFooRouteRoute
    }
  }
}

interface MethodsRouteRouteChildren {
  MethodsOnlyAnyRoute: typeof MethodsOnlyAnyRoute
  MethodsIndexRoute: typeof MethodsIndexRoute
}

const MethodsRouteRouteChildren: MethodsRouteRouteChildren = {
  MethodsOnlyAnyRoute: MethodsOnlyAnyRoute,
  MethodsIndexRoute: MethodsIndexRoute,
}

const MethodsRouteRouteWithChildren = MethodsRouteRoute._addFileChildren(
  MethodsRouteRouteChildren,
)

interface ApiParamsFooRouteRouteChildren {
  ApiParamsFooBarRoute: typeof ApiParamsFooBarRoute
}

const ApiParamsFooRouteRouteChildren: ApiParamsFooRouteRouteChildren = {
  ApiParamsFooBarRoute: ApiParamsFooBarRoute,
}

const ApiParamsFooRouteRouteWithChildren =
  ApiParamsFooRouteRoute._addFileChildren(ApiParamsFooRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MethodsRouteRoute: MethodsRouteRouteWithChildren,
  MergeMiddlewareContextRoute: MergeMiddlewareContextRoute,
  ApiMiddlewareContextRoute: ApiMiddlewareContextRoute,
  ApiOnlyAnyRoute: ApiOnlyAnyRoute,
  ApiHeadFallbackRoute: ApiHeadFallbackRoute,
  ApiGetAndAnyRoute: ApiGetAndAnyRoute,
  ApiHeadRedirectFallbackRoute: ApiHeadRedirectFallbackRoute,
  ApiParamsFooRouteRoute: ApiParamsFooRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
