/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SharedCRouteImport } from './routes/shared-c'
import { Route as SharedBRouteImport } from './routes/shared-b'
import { Route as SharedARouteImport } from './routes/shared-a'
import { Route as R6RouteImport } from './routes/r6'
import { Route as R5RouteImport } from './routes/r5'
import { Route as R4RouteImport } from './routes/r4'
import { Route as R3RouteImport } from './routes/r3'
import { Route as R2RouteImport } from './routes/r2'
import { Route as R1RouteImport } from './routes/r1'
import { Route as IndexRouteImport } from './routes/index'

const SharedCRoute = SharedCRouteImport.update({
  id: '/shared-c',
  path: '/shared-c',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedBRoute = SharedBRouteImport.update({
  id: '/shared-b',
  path: '/shared-b',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedARoute = SharedARouteImport.update({
  id: '/shared-a',
  path: '/shared-a',
  getParentRoute: () => rootRouteImport,
} as any)
const R6Route = R6RouteImport.update({
  id: '/r6',
  path: '/r6',
  getParentRoute: () => rootRouteImport,
} as any)
const R5Route = R5RouteImport.update({
  id: '/r5',
  path: '/r5',
  getParentRoute: () => rootRouteImport,
} as any)
const R4Route = R4RouteImport.update({
  id: '/r4',
  path: '/r4',
  getParentRoute: () => rootRouteImport,
} as any)
const R3Route = R3RouteImport.update({
  id: '/r3',
  path: '/r3',
  getParentRoute: () => rootRouteImport,
} as any)
const R2Route = R2RouteImport.update({
  id: '/r2',
  path: '/r2',
  getParentRoute: () => rootRouteImport,
} as any)
const R1Route = R1RouteImport.update({
  id: '/r1',
  path: '/r1',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/r1': typeof R1Route
  '/r2': typeof R2Route
  '/r3': typeof R3Route
  '/r4': typeof R4Route
  '/r5': typeof R5Route
  '/r6': typeof R6Route
  '/shared-a': typeof SharedARoute
  '/shared-b': typeof SharedBRoute
  '/shared-c': typeof SharedCRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/r1': typeof R1Route
  '/r2': typeof R2Route
  '/r3': typeof R3Route
  '/r4': typeof R4Route
  '/r5': typeof R5Route
  '/r6': typeof R6Route
  '/shared-a': typeof SharedARoute
  '/shared-b': typeof SharedBRoute
  '/shared-c': typeof SharedCRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/r1': typeof R1Route
  '/r2': typeof R2Route
  '/r3': typeof R3Route
  '/r4': typeof R4Route
  '/r5': typeof R5Route
  '/r6': typeof R6Route
  '/shared-a': typeof SharedARoute
  '/shared-b': typeof SharedBRoute
  '/shared-c': typeof SharedCRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/r1'
    | '/r2'
    | '/r3'
    | '/r4'
    | '/r5'
    | '/r6'
    | '/shared-a'
    | '/shared-b'
    | '/shared-c'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/r1'
    | '/r2'
    | '/r3'
    | '/r4'
    | '/r5'
    | '/r6'
    | '/shared-a'
    | '/shared-b'
    | '/shared-c'
  id:
    | '__root__'
    | '/'
    | '/r1'
    | '/r2'
    | '/r3'
    | '/r4'
    | '/r5'
    | '/r6'
    | '/shared-a'
    | '/shared-b'
    | '/shared-c'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R1Route: typeof R1Route
  R2Route: typeof R2Route
  R3Route: typeof R3Route
  R4Route: typeof R4Route
  R5Route: typeof R5Route
  R6Route: typeof R6Route
  SharedARoute: typeof SharedARoute
  SharedBRoute: typeof SharedBRoute
  SharedCRoute: typeof SharedCRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shared-c': {
      id: '/shared-c'
      path: '/shared-c'
      fullPath: '/shared-c'
      preLoaderRoute: typeof SharedCRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared-b': {
      id: '/shared-b'
      path: '/shared-b'
      fullPath: '/shared-b'
      preLoaderRoute: typeof SharedBRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared-a': {
      id: '/shared-a'
      path: '/shared-a'
      fullPath: '/shared-a'
      preLoaderRoute: typeof SharedARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r6': {
      id: '/r6'
      path: '/r6'
      fullPath: '/r6'
      preLoaderRoute: typeof R6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r5': {
      id: '/r5'
      path: '/r5'
      fullPath: '/r5'
      preLoaderRoute: typeof R5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r4': {
      id: '/r4'
      path: '/r4'
      fullPath: '/r4'
      preLoaderRoute: typeof R4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r3': {
      id: '/r3'
      path: '/r3'
      fullPath: '/r3'
      preLoaderRoute: typeof R3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r2': {
      id: '/r2'
      path: '/r2'
      fullPath: '/r2'
      preLoaderRoute: typeof R2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r1': {
      id: '/r1'
      path: '/r1'
      fullPath: '/r1'
      preLoaderRoute: typeof R1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R1Route: R1Route,
  R2Route: R2Route,
  R3Route: R3Route,
  R4Route: R4Route,
  R5Route: R5Route,
  R6Route: R6Route,
  SharedARoute: SharedARoute,
  SharedBRoute: SharedBRoute,
  SharedCRoute: SharedCRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
