/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SyncOnlyRouteImport } from './routes/sync-only'
import { Route as StreamingPolicyRouteImport } from './routes/streaming-policy'
import { Route as StreamRouteImport } from './routes/stream'
import { Route as SlowRenderRouteImport } from './routes/slow-render'
import { Route as QueryHeavyRouteImport } from './routes/query-heavy'
import { Route as NestedDeferredRouteImport } from './routes/nested-deferred'
import { Route as ManyPromisesRouteImport } from './routes/many-promises'
import { Route as FastSerialRouteImport } from './routes/fast-serial'
import { Route as DeferredRejectionRouteImport } from './routes/deferred-rejection'
import { Route as DeferredRouteImport } from './routes/deferred'
import { Route as ConcurrentRouteImport } from './routes/concurrent'
import { Route as IndexRouteImport } from './routes/index'

const SyncOnlyRoute = SyncOnlyRouteImport.update({
  id: '/sync-only',
  path: '/sync-only',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamingPolicyRoute = StreamingPolicyRouteImport.update({
  id: '/streaming-policy',
  path: '/streaming-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamRoute = StreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const SlowRenderRoute = SlowRenderRouteImport.update({
  id: '/slow-render',
  path: '/slow-render',
  getParentRoute: () => rootRouteImport,
} as any)
const QueryHeavyRoute = QueryHeavyRouteImport.update({
  id: '/query-heavy',
  path: '/query-heavy',
  getParentRoute: () => rootRouteImport,
} as any)
const NestedDeferredRoute = NestedDeferredRouteImport.update({
  id: '/nested-deferred',
  path: '/nested-deferred',
  getParentRoute: () => rootRouteImport,
} as any)
const ManyPromisesRoute = ManyPromisesRouteImport.update({
  id: '/many-promises',
  path: '/many-promises',
  getParentRoute: () => rootRouteImport,
} as any)
const FastSerialRoute = FastSerialRouteImport.update({
  id: '/fast-serial',
  path: '/fast-serial',
  getParentRoute: () => rootRouteImport,
} as any)
const DeferredRejectionRoute = DeferredRejectionRouteImport.update({
  id: '/deferred-rejection',
  path: '/deferred-rejection',
  getParentRoute: () => rootRouteImport,
} as any)
const DeferredRoute = DeferredRouteImport.update({
  id: '/deferred',
  path: '/deferred',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcurrentRoute = ConcurrentRouteImport.update({
  id: '/concurrent',
  path: '/concurrent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/concurrent': typeof ConcurrentRoute
  '/deferred': typeof DeferredRoute
  '/deferred-rejection': typeof DeferredRejectionRoute
  '/fast-serial': typeof FastSerialRoute
  '/many-promises': typeof ManyPromisesRoute
  '/nested-deferred': typeof NestedDeferredRoute
  '/query-heavy': typeof QueryHeavyRoute
  '/slow-render': typeof SlowRenderRoute
  '/stream': typeof StreamRoute
  '/streaming-policy': typeof StreamingPolicyRoute
  '/sync-only': typeof SyncOnlyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/concurrent': typeof ConcurrentRoute
  '/deferred': typeof DeferredRoute
  '/deferred-rejection': typeof DeferredRejectionRoute
  '/fast-serial': typeof FastSerialRoute
  '/many-promises': typeof ManyPromisesRoute
  '/nested-deferred': typeof NestedDeferredRoute
  '/query-heavy': typeof QueryHeavyRoute
  '/slow-render': typeof SlowRenderRoute
  '/stream': typeof StreamRoute
  '/streaming-policy': typeof StreamingPolicyRoute
  '/sync-only': typeof SyncOnlyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/concurrent': typeof ConcurrentRoute
  '/deferred': typeof DeferredRoute
  '/deferred-rejection': typeof DeferredRejectionRoute
  '/fast-serial': typeof FastSerialRoute
  '/many-promises': typeof ManyPromisesRoute
  '/nested-deferred': typeof NestedDeferredRoute
  '/query-heavy': typeof QueryHeavyRoute
  '/slow-render': typeof SlowRenderRoute
  '/stream': typeof StreamRoute
  '/streaming-policy': typeof StreamingPolicyRoute
  '/sync-only': typeof SyncOnlyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/concurrent'
    | '/deferred'
    | '/deferred-rejection'
    | '/fast-serial'
    | '/many-promises'
    | '/nested-deferred'
    | '/query-heavy'
    | '/slow-render'
    | '/stream'
    | '/streaming-policy'
    | '/sync-only'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/concurrent'
    | '/deferred'
    | '/deferred-rejection'
    | '/fast-serial'
    | '/many-promises'
    | '/nested-deferred'
    | '/query-heavy'
    | '/slow-render'
    | '/stream'
    | '/streaming-policy'
    | '/sync-only'
  id:
    | '__root__'
    | '/'
    | '/concurrent'
    | '/deferred'
    | '/deferred-rejection'
    | '/fast-serial'
    | '/many-promises'
    | '/nested-deferred'
    | '/query-heavy'
    | '/slow-render'
    | '/stream'
    | '/streaming-policy'
    | '/sync-only'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConcurrentRoute: typeof ConcurrentRoute
  DeferredRoute: typeof DeferredRoute
  DeferredRejectionRoute: typeof DeferredRejectionRoute
  FastSerialRoute: typeof FastSerialRoute
  ManyPromisesRoute: typeof ManyPromisesRoute
  NestedDeferredRoute: typeof NestedDeferredRoute
  QueryHeavyRoute: typeof QueryHeavyRoute
  SlowRenderRoute: typeof SlowRenderRoute
  StreamRoute: typeof StreamRoute
  StreamingPolicyRoute: typeof StreamingPolicyRoute
  SyncOnlyRoute: typeof SyncOnlyRoute
}

declare module '@tanstack/vue-router' {
  interface FileRoutesByPath {
    '/sync-only': {
      id: '/sync-only'
      path: '/sync-only'
      fullPath: '/sync-only'
      preLoaderRoute: typeof SyncOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streaming-policy': {
      id: '/streaming-policy'
      path: '/streaming-policy'
      fullPath: '/streaming-policy'
      preLoaderRoute: typeof StreamingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stream': {
      id: '/stream'
      path: '/stream'
      fullPath: '/stream'
      preLoaderRoute: typeof StreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slow-render': {
      id: '/slow-render'
      path: '/slow-render'
      fullPath: '/slow-render'
      preLoaderRoute: typeof SlowRenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/query-heavy': {
      id: '/query-heavy'
      path: '/query-heavy'
      fullPath: '/query-heavy'
      preLoaderRoute: typeof QueryHeavyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nested-deferred': {
      id: '/nested-deferred'
      path: '/nested-deferred'
      fullPath: '/nested-deferred'
      preLoaderRoute: typeof NestedDeferredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/many-promises': {
      id: '/many-promises'
      path: '/many-promises'
      fullPath: '/many-promises'
      preLoaderRoute: typeof ManyPromisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fast-serial': {
      id: '/fast-serial'
      path: '/fast-serial'
      fullPath: '/fast-serial'
      preLoaderRoute: typeof FastSerialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deferred-rejection': {
      id: '/deferred-rejection'
      path: '/deferred-rejection'
      fullPath: '/deferred-rejection'
      preLoaderRoute: typeof DeferredRejectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deferred': {
      id: '/deferred'
      path: '/deferred'
      fullPath: '/deferred'
      preLoaderRoute: typeof DeferredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concurrent': {
      id: '/concurrent'
      path: '/concurrent'
      fullPath: '/concurrent'
      preLoaderRoute: typeof ConcurrentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConcurrentRoute: ConcurrentRoute,
  DeferredRoute: DeferredRoute,
  DeferredRejectionRoute: DeferredRejectionRoute,
  FastSerialRoute: FastSerialRoute,
  ManyPromisesRoute: ManyPromisesRoute,
  NestedDeferredRoute: NestedDeferredRoute,
  QueryHeavyRoute: QueryHeavyRoute,
  SlowRenderRoute: SlowRenderRoute,
  StreamRoute: StreamRoute,
  StreamingPolicyRoute: StreamingPolicyRoute,
  SyncOnlyRoute: SyncOnlyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/vue-start'
declare module '@tanstack/vue-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
