/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as barBarRouteImport } from './routes/(bar)/_bar'
import { Route as fooAsdfLayoutRouteImport } from './routes/(foo)/asdf/_layout'
import { Route as barBarHelloRouteImport } from './routes/(bar)/_bar.hello'
import { Route as fooAsdfLayoutFooRouteImport } from './routes/(foo)/asdf/_layout.foo'
import { Route as fooAsdfbarIdRouteImport } from './routes/(foo)/asdf/(bar)/$id'
import { Route as fooAsdfanotherGroupLayoutRouteImport } from './routes/(foo)/asdf/(another-group)/_layout'
import { Route as fooAsdfbarLayoutAboutRouteImport } from './routes/(foo)/asdf/(bar)/_layout.about'
import { Route as fooAsdfanotherGroupLayoutBazRouteImport } from './routes/(foo)/asdf/(another-group)/_layout.baz'

const fooAsdfbarLayoutXyzLazyRouteImport = createFileRoute(
  '/(foo)/asdf/(bar)/_layout/xyz',
)()

const barBarRoute = barBarRouteImport.update({
  id: '/(bar)/_bar',
  getParentRoute: () => rootRouteImport,
} as any)
const fooAsdfLayoutRoute = fooAsdfLayoutRouteImport.update({
  id: '/(foo)/asdf/_layout',
  path: '/asdf',
  getParentRoute: () => rootRouteImport,
} as any)
const barBarHelloRoute = barBarHelloRouteImport.update({
  id: '/hello',
  path: '/hello',
  getParentRoute: () => barBarRoute,
} as any)
const fooAsdfLayoutFooRoute = fooAsdfLayoutFooRouteImport.update({
  id: '/foo',
  path: '/foo',
  getParentRoute: () => fooAsdfLayoutRoute,
} as any)
const fooAsdfbarIdRoute = fooAsdfbarIdRouteImport.update({
  id: '/(foo)/asdf/(bar)/$id',
  path: '/asdf/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const fooAsdfanotherGroupLayoutRoute =
  fooAsdfanotherGroupLayoutRouteImport.update({
    id: '/(foo)/asdf/(another-group)/_layout',
    path: '/asdf',
    getParentRoute: () => rootRouteImport,
  } as any)
const fooAsdfbarLayoutXyzLazyRoute = fooAsdfbarLayoutXyzLazyRouteImport
  .update({
    id: '/(foo)/asdf/(bar)/_layout/xyz',
    path: '/asdf/xyz',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(foo)/asdf/(bar)/_layout.xyz.lazy').then((d) => d.Route),
  )
const fooAsdfbarLayoutAboutRoute = fooAsdfbarLayoutAboutRouteImport.update({
  id: '/(foo)/asdf/(bar)/_layout/about',
  path: '/asdf/about',
  getParentRoute: () => rootRouteImport,
} as any)
const fooAsdfanotherGroupLayoutBazRoute =
  fooAsdfanotherGroupLayoutBazRouteImport.update({
    id: '/baz',
    path: '/baz',
    getParentRoute: () => fooAsdfanotherGroupLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/hello': typeof barBarHelloRoute
  '/asdf': typeof fooAsdfanotherGroupLayoutRouteWithChildren
  '/asdf/$id': typeof fooAsdfbarIdRoute
  '/asdf/foo': typeof fooAsdfLayoutFooRoute
  '/asdf/baz': typeof fooAsdfanotherGroupLayoutBazRoute
  '/asdf/about': typeof fooAsdfbarLayoutAboutRoute
  '/asdf/xyz': typeof fooAsdfbarLayoutXyzLazyRoute
}
export interface FileRoutesByTo {
  '/hello': typeof barBarHelloRoute
  '/asdf': typeof fooAsdfanotherGroupLayoutRouteWithChildren
  '/asdf/$id': typeof fooAsdfbarIdRoute
  '/asdf/foo': typeof fooAsdfLayoutFooRoute
  '/asdf/baz': typeof fooAsdfanotherGroupLayoutBazRoute
  '/asdf/about': typeof fooAsdfbarLayoutAboutRoute
  '/asdf/xyz': typeof fooAsdfbarLayoutXyzLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(bar)/_bar': typeof barBarRouteWithChildren
  '/(bar)/_bar/hello': typeof barBarHelloRoute
  '/(foo)/asdf/_layout': typeof fooAsdfLayoutRouteWithChildren
  '/(foo)/asdf/(another-group)/_layout': typeof fooAsdfanotherGroupLayoutRouteWithChildren
  '/(foo)/asdf/(bar)/$id': typeof fooAsdfbarIdRoute
  '/(foo)/asdf/_layout/foo': typeof fooAsdfLayoutFooRoute
  '/(foo)/asdf/(another-group)/_layout/baz': typeof fooAsdfanotherGroupLayoutBazRoute
  '/(foo)/asdf/(bar)/_layout/about': typeof fooAsdfbarLayoutAboutRoute
  '/(foo)/asdf/(bar)/_layout/xyz': typeof fooAsdfbarLayoutXyzLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/hello'
    | '/asdf'
    | '/asdf/$id'
    | '/asdf/foo'
    | '/asdf/baz'
    | '/asdf/about'
    | '/asdf/xyz'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/hello'
    | '/asdf'
    | '/asdf/$id'
    | '/asdf/foo'
    | '/asdf/baz'
    | '/asdf/about'
    | '/asdf/xyz'
  id:
    | '__root__'
    | '/(bar)/_bar'
    | '/(bar)/_bar/hello'
    | '/(foo)/asdf/_layout'
    | '/(foo)/asdf/(another-group)/_layout'
    | '/(foo)/asdf/(bar)/$id'
    | '/(foo)/asdf/_layout/foo'
    | '/(foo)/asdf/(another-group)/_layout/baz'
    | '/(foo)/asdf/(bar)/_layout/about'
    | '/(foo)/asdf/(bar)/_layout/xyz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  barBarRoute: typeof barBarRouteWithChildren
  fooAsdfLayoutRoute: typeof fooAsdfLayoutRouteWithChildren
  fooAsdfanotherGroupLayoutRoute: typeof fooAsdfanotherGroupLayoutRouteWithChildren
  fooAsdfbarIdRoute: typeof fooAsdfbarIdRoute
  fooAsdfbarLayoutAboutRoute: typeof fooAsdfbarLayoutAboutRoute
  fooAsdfbarLayoutXyzLazyRoute: typeof fooAsdfbarLayoutXyzLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(bar)/_bar': {
      id: '/(bar)/_bar'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof barBarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(foo)/asdf/_layout': {
      id: '/(foo)/asdf/_layout'
      path: '/asdf'
      fullPath: '/asdf'
      preLoaderRoute: typeof fooAsdfLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(bar)/_bar/hello': {
      id: '/(bar)/_bar/hello'
      path: '/hello'
      fullPath: '/hello'
      preLoaderRoute: typeof barBarHelloRouteImport
      parentRoute: typeof barBarRoute
    }
    '/(foo)/asdf/_layout/foo': {
      id: '/(foo)/asdf/_layout/foo'
      path: '/foo'
      fullPath: '/asdf/foo'
      preLoaderRoute: typeof fooAsdfLayoutFooRouteImport
      parentRoute: typeof fooAsdfLayoutRoute
    }
    '/(foo)/asdf/(bar)/$id': {
      id: '/(foo)/asdf/(bar)/$id'
      path: '/asdf/$id'
      fullPath: '/asdf/$id'
      preLoaderRoute: typeof fooAsdfbarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(foo)/asdf/(another-group)/_layout': {
      id: '/(foo)/asdf/(another-group)/_layout'
      path: '/asdf'
      fullPath: '/asdf'
      preLoaderRoute: typeof fooAsdfanotherGroupLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(foo)/asdf/(bar)/_layout/xyz': {
      id: '/(foo)/asdf/(bar)/_layout/xyz'
      path: '/asdf/xyz'
      fullPath: '/asdf/xyz'
      preLoaderRoute: typeof fooAsdfbarLayoutXyzLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(foo)/asdf/(bar)/_layout/about': {
      id: '/(foo)/asdf/(bar)/_layout/about'
      path: '/asdf/about'
      fullPath: '/asdf/about'
      preLoaderRoute: typeof fooAsdfbarLayoutAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(foo)/asdf/(another-group)/_layout/baz': {
      id: '/(foo)/asdf/(another-group)/_layout/baz'
      path: '/baz'
      fullPath: '/asdf/baz'
      preLoaderRoute: typeof fooAsdfanotherGroupLayoutBazRouteImport
      parentRoute: typeof fooAsdfanotherGroupLayoutRoute
    }
  }
}

interface barBarRouteChildren {
  barBarHelloRoute: typeof barBarHelloRoute
}

const barBarRouteChildren: barBarRouteChildren = {
  barBarHelloRoute: barBarHelloRoute,
}

const barBarRouteWithChildren =
  barBarRoute._addFileChildren(barBarRouteChildren)

interface fooAsdfLayoutRouteChildren {
  fooAsdfLayoutFooRoute: typeof fooAsdfLayoutFooRoute
}

const fooAsdfLayoutRouteChildren: fooAsdfLayoutRouteChildren = {
  fooAsdfLayoutFooRoute: fooAsdfLayoutFooRoute,
}

const fooAsdfLayoutRouteWithChildren = fooAsdfLayoutRoute._addFileChildren(
  fooAsdfLayoutRouteChildren,
)

interface fooAsdfanotherGroupLayoutRouteChildren {
  fooAsdfanotherGroupLayoutBazRoute: typeof fooAsdfanotherGroupLayoutBazRoute
}

const fooAsdfanotherGroupLayoutRouteChildren: fooAsdfanotherGroupLayoutRouteChildren =
  {
    fooAsdfanotherGroupLayoutBazRoute: fooAsdfanotherGroupLayoutBazRoute,
  }

const fooAsdfanotherGroupLayoutRouteWithChildren =
  fooAsdfanotherGroupLayoutRoute._addFileChildren(
    fooAsdfanotherGroupLayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  barBarRoute: barBarRouteWithChildren,
  fooAsdfLayoutRoute: fooAsdfLayoutRouteWithChildren,
  fooAsdfanotherGroupLayoutRoute: fooAsdfanotherGroupLayoutRouteWithChildren,
  fooAsdfbarIdRoute: fooAsdfbarIdRoute,
  fooAsdfbarLayoutAboutRoute: fooAsdfbarLayoutAboutRoute,
  fooAsdfbarLayoutXyzLazyRoute: fooAsdfbarLayoutXyzLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
