import { createServerRpc } from '@tanstack/react-start/server-rpc';
let withUseServer_createServerFn_handler;
let withoutUseServer_createServerFn_handler;
let withVariable_createServerFn_handler;
let withZodValidator_createServerFn_handler;
export { withUseServer_createServerFn_handler, withoutUseServer_createServerFn_handler, withVariable_createServerFn_handler, withZodValidator_createServerFn_handler };