/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as PostsPostIdIndexRouteImport } from './routes/posts.$postId.index'
import { Route as PostsPostIdDeepIndexRouteImport } from './routes/posts.$postId.deep.index'
import { Route as PostsPostIdDeepDepthRouteImport } from './routes/posts.$postId.deep.$depth'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdIndexRoute = PostsPostIdIndexRouteImport.update({
  id: '/posts/$postId/',
  path: '/posts/$postId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdDeepIndexRoute = PostsPostIdDeepIndexRouteImport.update({
  id: '/posts/$postId/deep/',
  path: '/posts/$postId/deep/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdDeepDepthRoute = PostsPostIdDeepDepthRouteImport.update({
  id: '/posts/$postId/deep/$depth',
  path: '/posts/$postId/deep/$depth',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/posts/': typeof PostsIndexRoute
  '/posts/$postId/': typeof PostsPostIdIndexRoute
  '/posts/$postId/deep/$depth': typeof PostsPostIdDeepDepthRoute
  '/posts/$postId/deep/': typeof PostsPostIdDeepIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/posts': typeof PostsIndexRoute
  '/posts/$postId': typeof PostsPostIdIndexRoute
  '/posts/$postId/deep/$depth': typeof PostsPostIdDeepDepthRoute
  '/posts/$postId/deep': typeof PostsPostIdDeepIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/posts/': typeof PostsIndexRoute
  '/posts/$postId/': typeof PostsPostIdIndexRoute
  '/posts/$postId/deep/$depth': typeof PostsPostIdDeepDepthRoute
  '/posts/$postId/deep/': typeof PostsPostIdDeepIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/posts/'
    | '/posts/$postId/'
    | '/posts/$postId/deep/$depth'
    | '/posts/$postId/deep/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/posts'
    | '/posts/$postId'
    | '/posts/$postId/deep/$depth'
    | '/posts/$postId/deep'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/posts/'
    | '/posts/$postId/'
    | '/posts/$postId/deep/$depth'
    | '/posts/$postId/deep/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PostsIndexRoute: typeof PostsIndexRoute
  PostsPostIdIndexRoute: typeof PostsPostIdIndexRoute
  PostsPostIdDeepDepthRoute: typeof PostsPostIdDeepDepthRoute
  PostsPostIdDeepIndexRoute: typeof PostsPostIdDeepIndexRoute
}

declare module '@tanstack/react-native-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId/': {
      id: '/posts/$postId/'
      path: '/posts/$postId'
      fullPath: '/posts/$postId/'
      preLoaderRoute: typeof PostsPostIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId/deep/': {
      id: '/posts/$postId/deep/'
      path: '/posts/$postId/deep'
      fullPath: '/posts/$postId/deep/'
      preLoaderRoute: typeof PostsPostIdDeepIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId/deep/$depth': {
      id: '/posts/$postId/deep/$depth'
      path: '/posts/$postId/deep/$depth'
      fullPath: '/posts/$postId/deep/$depth'
      preLoaderRoute: typeof PostsPostIdDeepDepthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PostsIndexRoute: PostsIndexRoute,
  PostsPostIdIndexRoute: PostsPostIdIndexRoute,
  PostsPostIdDeepDepthRoute: PostsPostIdDeepDepthRoute,
  PostsPostIdDeepIndexRoute: PostsPostIdDeepIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
