/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FooBarRouteImport } from './routes/foo/bar'
import { Route as fooBarDetailsRouteImport } from './routes/foo/bar/details'
import { Route as fooBarHomeRouteImport } from './routes/foo/bar/home'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FooBarRoute = FooBarRouteImport.update({
  id: '/foo/bar',
  path: '/foo/bar',
  getParentRoute: () => rootRouteImport,
} as any)
const fooBarDetailsRoute = fooBarDetailsRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FooBarRoute,
} as any)
const fooBarHomeRoute = fooBarHomeRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FooBarRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/foo/bar': typeof FooBarRouteWithChildren
  '/foo/bar/': typeof fooBarHomeRoute
  '/foo/bar/$id': typeof fooBarDetailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/foo/bar': typeof fooBarHomeRoute
  '/foo/bar/$id': typeof fooBarDetailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/foo/bar': typeof FooBarRouteWithChildren
  '/foo/bar/': typeof fooBarHomeRoute
  '/foo/bar/$id': typeof fooBarDetailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/foo/bar' | '/foo/bar/' | '/foo/bar/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/foo/bar' | '/foo/bar/$id'
  id: '__root__' | '/' | '/foo/bar' | '/foo/bar/' | '/foo/bar/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FooBarRoute: typeof FooBarRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foo/bar': {
      id: '/foo/bar'
      path: '/foo/bar'
      fullPath: '/foo/bar'
      preLoaderRoute: typeof FooBarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foo/bar/$id': {
      id: '/foo/bar/$id'
      path: '/$id'
      fullPath: '/foo/bar/$id'
      preLoaderRoute: typeof fooBarDetailsRouteImport
      parentRoute: typeof FooBarRoute
    }
    '/foo/bar/': {
      id: '/foo/bar/'
      path: '/'
      fullPath: '/foo/bar/'
      preLoaderRoute: typeof fooBarHomeRouteImport
      parentRoute: typeof FooBarRoute
    }
  }
}

interface FooBarRouteChildren {
  fooBarHomeRoute: typeof fooBarHomeRoute
  fooBarDetailsRoute: typeof fooBarDetailsRoute
}

const FooBarRouteChildren: FooBarRouteChildren = {
  fooBarHomeRoute: fooBarHomeRoute,
  fooBarDetailsRoute: fooBarDetailsRoute,
}

const FooBarRouteWithChildren =
  FooBarRoute._addFileChildren(FooBarRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FooBarRoute: FooBarRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
