/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char91__rootIndexChar93IndexRouteImport } from './routes/[__root-index]/index'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as FooRouteImport } from './routes/[_]foo'
import { Route as Char91__literalChar93RouteImport } from './routes/[__literal]'
import { Route as _layoutRouteImport } from './routes/__layout'
import { Route as RootIndexIndexRouteImport } from './routes/[_]root-index/index'
import { Route as LayoutNestedRouteImport } from './routes/_layout/_nested'
import { Route as LayoutBarRouteImport } from './routes/_layout/[_]bar'
import { Route as Layout_nested2RouteImport } from './routes/_layout/__nested2'
import { Route as LayoutChar91__doubleChar93RouteImport } from './routes/_layout/[__double]'
import { Route as _layoutQuxRouteImport } from './routes/__layout/[_]qux'
import { Route as LayoutNestedTrailingIndexRouteImport } from './routes/_layout/nested-trailing[_]/index'
import { Route as LayoutNestedIndexIndexRouteImport } from './routes/_layout/[_]nested-index/index'
import { Route as LayoutChar91__doubleIndexChar93IndexRouteImport } from './routes/_layout/[__double-index]/index'
import { Route as LayoutNestedBazRouteImport } from './routes/_layout/_nested/[_]baz'
import { Route as LayoutNestedIndexIdRouteImport } from './routes/_layout/[_]nested-index/$id'
import { Route as Layout_nested2DeepRouteImport } from './routes/_layout/__nested2/[_]deep'
import { Route as LayoutChar91__doubleIndexChar93IdRouteImport } from './routes/_layout/[__double-index]/$id'
import { Route as LayoutNestedDeepIndexIndexRouteImport } from './routes/_layout/_nested/[_]deep-index/index'

const Char91__rootIndexChar93IndexRoute =
  Char91__rootIndexChar93IndexRouteImport.update({
    id: '/__root-index/',
    path: '/__root-index/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const FooRoute = FooRouteImport.update({
  id: '/_foo',
  path: '/_foo',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91__literalChar93Route = Char91__literalChar93RouteImport.update({
  id: '/__literal',
  path: '/__literal',
  getParentRoute: () => rootRouteImport,
} as any)
const _layoutRoute = _layoutRouteImport.update({
  id: '/__layout',
  getParentRoute: () => rootRouteImport,
} as any)
const RootIndexIndexRoute = RootIndexIndexRouteImport.update({
  id: '/_root-index/',
  path: '/_root-index/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutNestedRoute = LayoutNestedRouteImport.update({
  id: '/_nested',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBarRoute = LayoutBarRouteImport.update({
  id: '/_bar',
  path: '/_bar',
  getParentRoute: () => LayoutRoute,
} as any)
const Layout_nested2Route = Layout_nested2RouteImport.update({
  id: '/__nested2',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChar91__doubleChar93Route =
  LayoutChar91__doubleChar93RouteImport.update({
    id: '/__double',
    path: '/__double',
    getParentRoute: () => LayoutRoute,
  } as any)
const _layoutQuxRoute = _layoutQuxRouteImport.update({
  id: '/_qux',
  path: '/_qux',
  getParentRoute: () => _layoutRoute,
} as any)
const LayoutNestedTrailingIndexRoute =
  LayoutNestedTrailingIndexRouteImport.update({
    id: '/nested-trailing_/',
    path: '/nested-trailing_/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutNestedIndexIndexRoute = LayoutNestedIndexIndexRouteImport.update({
  id: '/_nested-index/',
  path: '/_nested-index/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChar91__doubleIndexChar93IndexRoute =
  LayoutChar91__doubleIndexChar93IndexRouteImport.update({
    id: '/__double-index/',
    path: '/__double-index/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutNestedBazRoute = LayoutNestedBazRouteImport.update({
  id: '/_baz',
  path: '/_baz',
  getParentRoute: () => LayoutNestedRoute,
} as any)
const LayoutNestedIndexIdRoute = LayoutNestedIndexIdRouteImport.update({
  id: '/_nested-index/$id',
  path: '/_nested-index/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const Layout_nested2DeepRoute = Layout_nested2DeepRouteImport.update({
  id: '/_deep',
  path: '/_deep',
  getParentRoute: () => Layout_nested2Route,
} as any)
const LayoutChar91__doubleIndexChar93IdRoute =
  LayoutChar91__doubleIndexChar93IdRouteImport.update({
    id: '/__double-index/$id',
    path: '/__double-index/$id',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutNestedDeepIndexIndexRoute =
  LayoutNestedDeepIndexIndexRouteImport.update({
    id: '/_deep-index/',
    path: '/_deep-index/',
    getParentRoute: () => LayoutNestedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutNestedRouteWithChildren
  '/__literal': typeof Char91__literalChar93Route
  '/_foo': typeof FooRoute
  '/_qux': typeof _layoutQuxRoute
  '/__double': typeof LayoutChar91__doubleChar93Route
  '/_bar': typeof LayoutBarRoute
  '/__root-index/': typeof Char91__rootIndexChar93IndexRoute
  '/_root-index/': typeof RootIndexIndexRoute
  '/__double-index/$id': typeof LayoutChar91__doubleIndexChar93IdRoute
  '/_deep': typeof Layout_nested2DeepRoute
  '/_nested-index/$id': typeof LayoutNestedIndexIdRoute
  '/_baz': typeof LayoutNestedBazRoute
  '/__double-index/': typeof LayoutChar91__doubleIndexChar93IndexRoute
  '/_nested-index/': typeof LayoutNestedIndexIndexRoute
  '/nested-trailing_/': typeof LayoutNestedTrailingIndexRoute
  '/_deep-index/': typeof LayoutNestedDeepIndexIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutNestedRouteWithChildren
  '/__literal': typeof Char91__literalChar93Route
  '/_foo': typeof FooRoute
  '/_qux': typeof _layoutQuxRoute
  '/__double': typeof LayoutChar91__doubleChar93Route
  '/_bar': typeof LayoutBarRoute
  '/__root-index': typeof Char91__rootIndexChar93IndexRoute
  '/_root-index': typeof RootIndexIndexRoute
  '/__double-index/$id': typeof LayoutChar91__doubleIndexChar93IdRoute
  '/_deep': typeof Layout_nested2DeepRoute
  '/_nested-index/$id': typeof LayoutNestedIndexIdRoute
  '/_baz': typeof LayoutNestedBazRoute
  '/__double-index': typeof LayoutChar91__doubleIndexChar93IndexRoute
  '/_nested-index': typeof LayoutNestedIndexIndexRoute
  '/nested-trailing_': typeof LayoutNestedTrailingIndexRoute
  '/_deep-index': typeof LayoutNestedDeepIndexIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__layout': typeof _layoutRouteWithChildren
  '/__literal': typeof Char91__literalChar93Route
  '/_foo': typeof FooRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/__layout/_qux': typeof _layoutQuxRoute
  '/_layout/__double': typeof LayoutChar91__doubleChar93Route
  '/_layout/__nested2': typeof Layout_nested2RouteWithChildren
  '/_layout/_bar': typeof LayoutBarRoute
  '/_layout/_nested': typeof LayoutNestedRouteWithChildren
  '/__root-index/': typeof Char91__rootIndexChar93IndexRoute
  '/_root-index/': typeof RootIndexIndexRoute
  '/_layout/__double-index/$id': typeof LayoutChar91__doubleIndexChar93IdRoute
  '/_layout/__nested2/_deep': typeof Layout_nested2DeepRoute
  '/_layout/_nested-index/$id': typeof LayoutNestedIndexIdRoute
  '/_layout/_nested/_baz': typeof LayoutNestedBazRoute
  '/_layout/__double-index/': typeof LayoutChar91__doubleIndexChar93IndexRoute
  '/_layout/_nested-index/': typeof LayoutNestedIndexIndexRoute
  '/_layout/nested-trailing_/': typeof LayoutNestedTrailingIndexRoute
  '/_layout/_nested/_deep-index/': typeof LayoutNestedDeepIndexIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/__literal'
    | '/_foo'
    | '/_qux'
    | '/__double'
    | '/_bar'
    | '/__root-index/'
    | '/_root-index/'
    | '/__double-index/$id'
    | '/_deep'
    | '/_nested-index/$id'
    | '/_baz'
    | '/__double-index/'
    | '/_nested-index/'
    | '/nested-trailing_/'
    | '/_deep-index/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/__literal'
    | '/_foo'
    | '/_qux'
    | '/__double'
    | '/_bar'
    | '/__root-index'
    | '/_root-index'
    | '/__double-index/$id'
    | '/_deep'
    | '/_nested-index/$id'
    | '/_baz'
    | '/__double-index'
    | '/_nested-index'
    | '/nested-trailing_'
    | '/_deep-index'
  id:
    | '__root__'
    | '/__layout'
    | '/__literal'
    | '/_foo'
    | '/_layout'
    | '/__layout/_qux'
    | '/_layout/__double'
    | '/_layout/__nested2'
    | '/_layout/_bar'
    | '/_layout/_nested'
    | '/__root-index/'
    | '/_root-index/'
    | '/_layout/__double-index/$id'
    | '/_layout/__nested2/_deep'
    | '/_layout/_nested-index/$id'
    | '/_layout/_nested/_baz'
    | '/_layout/__double-index/'
    | '/_layout/_nested-index/'
    | '/_layout/nested-trailing_/'
    | '/_layout/_nested/_deep-index/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _layoutRoute: typeof _layoutRouteWithChildren
  Char91__literalChar93Route: typeof Char91__literalChar93Route
  FooRoute: typeof FooRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  Char91__rootIndexChar93IndexRoute: typeof Char91__rootIndexChar93IndexRoute
  RootIndexIndexRoute: typeof RootIndexIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__root-index/': {
      id: '/__root-index/'
      path: '/__root-index'
      fullPath: '/__root-index/'
      preLoaderRoute: typeof Char91__rootIndexChar93IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_foo': {
      id: '/_foo'
      path: '/_foo'
      fullPath: '/_foo'
      preLoaderRoute: typeof FooRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__literal': {
      id: '/__literal'
      path: '/__literal'
      fullPath: '/__literal'
      preLoaderRoute: typeof Char91__literalChar93RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__layout': {
      id: '/__layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof _layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_root-index/': {
      id: '/_root-index/'
      path: '/_root-index'
      fullPath: '/_root-index/'
      preLoaderRoute: typeof RootIndexIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_nested': {
      id: '/_layout/_nested'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutNestedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_bar': {
      id: '/_layout/_bar'
      path: '/_bar'
      fullPath: '/_bar'
      preLoaderRoute: typeof LayoutBarRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/__nested2': {
      id: '/_layout/__nested2'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof Layout_nested2RouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/__double': {
      id: '/_layout/__double'
      path: '/__double'
      fullPath: '/__double'
      preLoaderRoute: typeof LayoutChar91__doubleChar93RouteImport
      parentRoute: typeof LayoutRoute
    }
    '/__layout/_qux': {
      id: '/__layout/_qux'
      path: '/_qux'
      fullPath: '/_qux'
      preLoaderRoute: typeof _layoutQuxRouteImport
      parentRoute: typeof _layoutRoute
    }
    '/_layout/nested-trailing_/': {
      id: '/_layout/nested-trailing_/'
      path: '/nested-trailing_'
      fullPath: '/nested-trailing_/'
      preLoaderRoute: typeof LayoutNestedTrailingIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_nested-index/': {
      id: '/_layout/_nested-index/'
      path: '/_nested-index'
      fullPath: '/_nested-index/'
      preLoaderRoute: typeof LayoutNestedIndexIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/__double-index/': {
      id: '/_layout/__double-index/'
      path: '/__double-index'
      fullPath: '/__double-index/'
      preLoaderRoute: typeof LayoutChar91__doubleIndexChar93IndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_nested/_baz': {
      id: '/_layout/_nested/_baz'
      path: '/_baz'
      fullPath: '/_baz'
      preLoaderRoute: typeof LayoutNestedBazRouteImport
      parentRoute: typeof LayoutNestedRoute
    }
    '/_layout/_nested-index/$id': {
      id: '/_layout/_nested-index/$id'
      path: '/_nested-index/$id'
      fullPath: '/_nested-index/$id'
      preLoaderRoute: typeof LayoutNestedIndexIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/__nested2/_deep': {
      id: '/_layout/__nested2/_deep'
      path: '/_deep'
      fullPath: '/_deep'
      preLoaderRoute: typeof Layout_nested2DeepRouteImport
      parentRoute: typeof Layout_nested2Route
    }
    '/_layout/__double-index/$id': {
      id: '/_layout/__double-index/$id'
      path: '/__double-index/$id'
      fullPath: '/__double-index/$id'
      preLoaderRoute: typeof LayoutChar91__doubleIndexChar93IdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_nested/_deep-index/': {
      id: '/_layout/_nested/_deep-index/'
      path: '/_deep-index'
      fullPath: '/_deep-index/'
      preLoaderRoute: typeof LayoutNestedDeepIndexIndexRouteImport
      parentRoute: typeof LayoutNestedRoute
    }
  }
}

interface _layoutRouteChildren {
  _layoutQuxRoute: typeof _layoutQuxRoute
}

const _layoutRouteChildren: _layoutRouteChildren = {
  _layoutQuxRoute: _layoutQuxRoute,
}

const _layoutRouteWithChildren =
  _layoutRoute._addFileChildren(_layoutRouteChildren)

interface Layout_nested2RouteChildren {
  Layout_nested2DeepRoute: typeof Layout_nested2DeepRoute
}

const Layout_nested2RouteChildren: Layout_nested2RouteChildren = {
  Layout_nested2DeepRoute: Layout_nested2DeepRoute,
}

const Layout_nested2RouteWithChildren = Layout_nested2Route._addFileChildren(
  Layout_nested2RouteChildren,
)

interface LayoutNestedRouteChildren {
  LayoutNestedBazRoute: typeof LayoutNestedBazRoute
  LayoutNestedDeepIndexIndexRoute: typeof LayoutNestedDeepIndexIndexRoute
}

const LayoutNestedRouteChildren: LayoutNestedRouteChildren = {
  LayoutNestedBazRoute: LayoutNestedBazRoute,
  LayoutNestedDeepIndexIndexRoute: LayoutNestedDeepIndexIndexRoute,
}

const LayoutNestedRouteWithChildren = LayoutNestedRoute._addFileChildren(
  LayoutNestedRouteChildren,
)

interface LayoutRouteChildren {
  LayoutChar91__doubleChar93Route: typeof LayoutChar91__doubleChar93Route
  Layout_nested2Route: typeof Layout_nested2RouteWithChildren
  LayoutBarRoute: typeof LayoutBarRoute
  LayoutNestedRoute: typeof LayoutNestedRouteWithChildren
  LayoutChar91__doubleIndexChar93IdRoute: typeof LayoutChar91__doubleIndexChar93IdRoute
  LayoutNestedIndexIdRoute: typeof LayoutNestedIndexIdRoute
  LayoutChar91__doubleIndexChar93IndexRoute: typeof LayoutChar91__doubleIndexChar93IndexRoute
  LayoutNestedIndexIndexRoute: typeof LayoutNestedIndexIndexRoute
  LayoutNestedTrailingIndexRoute: typeof LayoutNestedTrailingIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutChar91__doubleChar93Route: LayoutChar91__doubleChar93Route,
  Layout_nested2Route: Layout_nested2RouteWithChildren,
  LayoutBarRoute: LayoutBarRoute,
  LayoutNestedRoute: LayoutNestedRouteWithChildren,
  LayoutChar91__doubleIndexChar93IdRoute:
    LayoutChar91__doubleIndexChar93IdRoute,
  LayoutNestedIndexIdRoute: LayoutNestedIndexIdRoute,
  LayoutChar91__doubleIndexChar93IndexRoute:
    LayoutChar91__doubleIndexChar93IndexRoute,
  LayoutNestedIndexIndexRoute: LayoutNestedIndexIndexRoute,
  LayoutNestedTrailingIndexRoute: LayoutNestedTrailingIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  _layoutRoute: _layoutRouteWithChildren,
  Char91__literalChar93Route: Char91__literalChar93Route,
  FooRoute: FooRoute,
  LayoutRoute: LayoutRouteWithChildren,
  Char91__rootIndexChar93IndexRoute: Char91__rootIndexChar93IndexRoute,
  RootIndexIndexRoute: RootIndexIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
