/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as PostsRouteRouteImport } from './routes/posts/route'
import { Route as BlogRouteRouteImport } from './routes/blog/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogStatsRouteImport } from './routes/blog_/stats'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as BlogBlogIdRouteRouteImport } from './routes/blog_/$blogId/route'
import { Route as PostsPostIdIndexRouteImport } from './routes/posts/$postId/index'
import { Route as PostsPostIdDeepRouteImport } from './routes/posts/$postId/deep'
import { Route as BlogBlogIdEditRouteImport } from './routes/blog_/$blogId_/edit'
import { Route as BlogBlogIdSlugRouteRouteImport } from './routes/blog_/$blogId/$slug/route'
import { Route as BlogBlogIdSlugBarRouteImport } from './routes/blog_/$blogId/$slug_/bar'

const PostsRouteRoute = PostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRouteRoute = BlogRouteRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRouteRoute,
} as any)
const BlogStatsRoute = BlogStatsRouteImport.update({
  id: '/blog/stats',
  path: '/blog/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRouteRoute,
} as any)
const BlogBlogIdRouteRoute = BlogBlogIdRouteRouteImport.update({
  id: '/blog/$blogId',
  path: '/blog/$blogId',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdIndexRoute = PostsPostIdIndexRouteImport.update({
  id: '/$postId/',
  path: '/$postId/',
  getParentRoute: () => PostsRouteRoute,
} as any)
const PostsPostIdDeepRoute = PostsPostIdDeepRouteImport.update({
  id: '/$postId/deep',
  path: '/$postId/deep',
  getParentRoute: () => PostsRouteRoute,
} as any)
const BlogBlogIdEditRoute = BlogBlogIdEditRouteImport.update({
  id: '/blog/$blogId/edit',
  path: '/blog/$blogId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogBlogIdSlugRouteRoute = BlogBlogIdSlugRouteRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogBlogIdRouteRoute,
} as any)
const BlogBlogIdSlugBarRoute = BlogBlogIdSlugBarRouteImport.update({
  id: '/$slug/bar',
  path: '/$slug/bar',
  getParentRoute: () => BlogBlogIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteRouteWithChildren
  '/posts': typeof PostsRouteRouteWithChildren
  '/blog/$blogId': typeof BlogBlogIdRouteRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/stats': typeof BlogStatsRoute
  '/blog/': typeof BlogIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/blog/$blogId/$slug': typeof BlogBlogIdSlugRouteRoute
  '/blog/$blogId/edit': typeof BlogBlogIdEditRoute
  '/posts/$postId/deep': typeof PostsPostIdDeepRoute
  '/posts/$postId': typeof PostsPostIdIndexRoute
  '/blog/$blogId/$slug/bar': typeof BlogBlogIdSlugBarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog/$blogId': typeof BlogBlogIdRouteRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/stats': typeof BlogStatsRoute
  '/blog': typeof BlogIndexRoute
  '/posts': typeof PostsIndexRoute
  '/blog/$blogId/$slug': typeof BlogBlogIdSlugRouteRoute
  '/blog/$blogId/edit': typeof BlogBlogIdEditRoute
  '/posts/$postId/deep': typeof PostsPostIdDeepRoute
  '/posts/$postId': typeof PostsPostIdIndexRoute
  '/blog/$blogId/$slug/bar': typeof BlogBlogIdSlugBarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteRouteWithChildren
  '/posts': typeof PostsRouteRouteWithChildren
  '/blog/$blogId': typeof BlogBlogIdRouteRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/stats': typeof BlogStatsRoute
  '/blog/': typeof BlogIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/blog/$blogId/$slug': typeof BlogBlogIdSlugRouteRoute
  '/blog/$blogId/edit': typeof BlogBlogIdEditRoute
  '/posts/$postId/deep': typeof PostsPostIdDeepRoute
  '/posts/$postId/': typeof PostsPostIdIndexRoute
  '/blog/$blogId/$slug/bar': typeof BlogBlogIdSlugBarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/posts'
    | '/blog/$blogId'
    | '/blog/$slug'
    | '/blog/stats'
    | '/blog/'
    | '/posts/'
    | '/blog/$blogId/$slug'
    | '/blog/$blogId/edit'
    | '/posts/$postId/deep'
    | '/posts/$postId'
    | '/blog/$blogId/$slug/bar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog/$blogId'
    | '/blog/$slug'
    | '/blog/stats'
    | '/blog'
    | '/posts'
    | '/blog/$blogId/$slug'
    | '/blog/$blogId/edit'
    | '/posts/$postId/deep'
    | '/posts/$postId'
    | '/blog/$blogId/$slug/bar'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/posts'
    | '/blog/$blogId'
    | '/blog/$slug'
    | '/blog/stats'
    | '/blog/'
    | '/posts/'
    | '/blog/$blogId/$slug'
    | '/blog/$blogId/edit'
    | '/posts/$postId/deep'
    | '/posts/$postId/'
    | '/blog/$blogId/$slug/bar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRouteRoute: typeof BlogRouteRouteWithChildren
  PostsRouteRoute: typeof PostsRouteRouteWithChildren
  BlogBlogIdRouteRoute: typeof BlogBlogIdRouteRouteWithChildren
  BlogStatsRoute: typeof BlogStatsRoute
  BlogBlogIdEditRoute: typeof BlogBlogIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/blog/stats': {
      id: '/blog/stats'
      path: '/blog/stats'
      fullPath: '/blog/stats'
      preLoaderRoute: typeof BlogStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/blog/$blogId': {
      id: '/blog/$blogId'
      path: '/blog/$blogId'
      fullPath: '/blog/$blogId'
      preLoaderRoute: typeof BlogBlogIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId/': {
      id: '/posts/$postId/'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdIndexRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/posts/$postId/deep': {
      id: '/posts/$postId/deep'
      path: '/$postId/deep'
      fullPath: '/posts/$postId/deep'
      preLoaderRoute: typeof PostsPostIdDeepRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/blog/$blogId/edit': {
      id: '/blog/$blogId/edit'
      path: '/blog/$blogId/edit'
      fullPath: '/blog/$blogId/edit'
      preLoaderRoute: typeof BlogBlogIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$blogId/$slug': {
      id: '/blog/$blogId/$slug'
      path: '/$slug'
      fullPath: '/blog/$blogId/$slug'
      preLoaderRoute: typeof BlogBlogIdSlugRouteRouteImport
      parentRoute: typeof BlogBlogIdRouteRoute
    }
    '/blog/$blogId/$slug/bar': {
      id: '/blog/$blogId/$slug/bar'
      path: '/$slug/bar'
      fullPath: '/blog/$blogId/$slug/bar'
      preLoaderRoute: typeof BlogBlogIdSlugBarRouteImport
      parentRoute: typeof BlogBlogIdRouteRoute
    }
  }
}

declare module './routes/index' {
  const createFileRoute: CreateFileRoute<
    '/',
    FileRoutesByPath['/']['parentRoute'],
    FileRoutesByPath['/']['id'],
    FileRoutesByPath['/']['path'],
    FileRoutesByPath['/']['fullPath']
  >
}
declare module './routes/blog/route' {
  const createFileRoute: CreateFileRoute<
    '/blog',
    FileRoutesByPath['/blog']['parentRoute'],
    FileRoutesByPath['/blog']['id'],
    FileRoutesByPath['/blog']['path'],
    FileRoutesByPath['/blog']['fullPath']
  >
}
declare module './routes/posts/route' {
  const createFileRoute: CreateFileRoute<
    '/posts',
    FileRoutesByPath['/posts']['parentRoute'],
    FileRoutesByPath['/posts']['id'],
    FileRoutesByPath['/posts']['path'],
    FileRoutesByPath['/posts']['fullPath']
  >
}
declare module './routes/blog_/$blogId/route' {
  const createFileRoute: CreateFileRoute<
    '/blog/$blogId',
    FileRoutesByPath['/blog/$blogId']['parentRoute'],
    FileRoutesByPath['/blog/$blogId']['id'],
    FileRoutesByPath['/blog/$blogId']['path'],
    FileRoutesByPath['/blog/$blogId']['fullPath']
  >
}
declare module './routes/blog/$slug' {
  const createFileRoute: CreateFileRoute<
    '/blog/$slug',
    FileRoutesByPath['/blog/$slug']['parentRoute'],
    FileRoutesByPath['/blog/$slug']['id'],
    FileRoutesByPath['/blog/$slug']['path'],
    FileRoutesByPath['/blog/$slug']['fullPath']
  >
}
declare module './routes/blog_/stats' {
  const createFileRoute: CreateFileRoute<
    '/blog/stats',
    FileRoutesByPath['/blog/stats']['parentRoute'],
    FileRoutesByPath['/blog/stats']['id'],
    FileRoutesByPath['/blog/stats']['path'],
    FileRoutesByPath['/blog/stats']['fullPath']
  >
}
declare module './routes/blog/index' {
  const createFileRoute: CreateFileRoute<
    '/blog/',
    FileRoutesByPath['/blog/']['parentRoute'],
    FileRoutesByPath['/blog/']['id'],
    FileRoutesByPath['/blog/']['path'],
    FileRoutesByPath['/blog/']['fullPath']
  >
}
declare module './routes/posts/index' {
  const createFileRoute: CreateFileRoute<
    '/posts/',
    FileRoutesByPath['/posts/']['parentRoute'],
    FileRoutesByPath['/posts/']['id'],
    FileRoutesByPath['/posts/']['path'],
    FileRoutesByPath['/posts/']['fullPath']
  >
}
declare module './routes/blog_/$blogId/$slug/route' {
  const createFileRoute: CreateFileRoute<
    '/blog/$blogId/$slug',
    FileRoutesByPath['/blog/$blogId/$slug']['parentRoute'],
    FileRoutesByPath['/blog/$blogId/$slug']['id'],
    FileRoutesByPath['/blog/$blogId/$slug']['path'],
    FileRoutesByPath['/blog/$blogId/$slug']['fullPath']
  >
}
declare module './routes/blog_/$blogId_/edit' {
  const createFileRoute: CreateFileRoute<
    '/blog/$blogId/edit',
    FileRoutesByPath['/blog/$blogId/edit']['parentRoute'],
    FileRoutesByPath['/blog/$blogId/edit']['id'],
    FileRoutesByPath['/blog/$blogId/edit']['path'],
    FileRoutesByPath['/blog/$blogId/edit']['fullPath']
  >
}
declare module './routes/posts/$postId/deep' {
  const createFileRoute: CreateFileRoute<
    '/posts/$postId/deep',
    FileRoutesByPath['/posts/$postId/deep']['parentRoute'],
    FileRoutesByPath['/posts/$postId/deep']['id'],
    FileRoutesByPath['/posts/$postId/deep']['path'],
    FileRoutesByPath['/posts/$postId/deep']['fullPath']
  >
}
declare module './routes/posts/$postId/index' {
  const createFileRoute: CreateFileRoute<
    '/posts/$postId/',
    FileRoutesByPath['/posts/$postId/']['parentRoute'],
    FileRoutesByPath['/posts/$postId/']['id'],
    FileRoutesByPath['/posts/$postId/']['path'],
    FileRoutesByPath['/posts/$postId/']['fullPath']
  >
}
declare module './routes/blog_/$blogId/$slug_/bar' {
  const createFileRoute: CreateFileRoute<
    '/blog/$blogId/$slug/bar',
    FileRoutesByPath['/blog/$blogId/$slug/bar']['parentRoute'],
    FileRoutesByPath['/blog/$blogId/$slug/bar']['id'],
    FileRoutesByPath['/blog/$blogId/$slug/bar']['path'],
    FileRoutesByPath['/blog/$blogId/$slug/bar']['fullPath']
  >
}

interface BlogRouteRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteRouteChildren: BlogRouteRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteRouteWithChildren = BlogRouteRoute._addFileChildren(
  BlogRouteRouteChildren,
)

interface PostsRouteRouteChildren {
  PostsIndexRoute: typeof PostsIndexRoute
  PostsPostIdDeepRoute: typeof PostsPostIdDeepRoute
  PostsPostIdIndexRoute: typeof PostsPostIdIndexRoute
}

const PostsRouteRouteChildren: PostsRouteRouteChildren = {
  PostsIndexRoute: PostsIndexRoute,
  PostsPostIdDeepRoute: PostsPostIdDeepRoute,
  PostsPostIdIndexRoute: PostsPostIdIndexRoute,
}

const PostsRouteRouteWithChildren = PostsRouteRoute._addFileChildren(
  PostsRouteRouteChildren,
)

interface BlogBlogIdRouteRouteChildren {
  BlogBlogIdSlugRouteRoute: typeof BlogBlogIdSlugRouteRoute
  BlogBlogIdSlugBarRoute: typeof BlogBlogIdSlugBarRoute
}

const BlogBlogIdRouteRouteChildren: BlogBlogIdRouteRouteChildren = {
  BlogBlogIdSlugRouteRoute: BlogBlogIdSlugRouteRoute,
  BlogBlogIdSlugBarRoute: BlogBlogIdSlugBarRoute,
}

const BlogBlogIdRouteRouteWithChildren = BlogBlogIdRouteRoute._addFileChildren(
  BlogBlogIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRouteRoute: BlogRouteRouteWithChildren,
  PostsRouteRoute: PostsRouteRouteWithChildren,
  BlogBlogIdRouteRoute: BlogBlogIdRouteRouteWithChildren,
  BlogStatsRoute: BlogStatsRoute,
  BlogBlogIdEditRoute: BlogBlogIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
