name: Changeset Preview

on:
  pull_request:
    paths:
      - '.changeset/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  preview:
    name: Version Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
      - name: Setup Tools
        uses: TanStack/config/.github/setup@main
      - name: Changeset Preview
        uses: TanStack/config/.github/changeset-preview@main
